packages:
  - "packages/*"
  - "apps/*"
  - "integrations/*"
onlyBuiltDependencies:
  - "@primno/dpapi"
  - esbuild
  - electron
allowBuilds:
  "@primno/dpapi": true
  esbuild: true
  electron: true
  electron-winstaller: false
