import { useEffect, useRef, useState, type SyntheticEvent } from "react";
import { researchRoomApi } from "../../api/client.js";
import type {
  AppLanguage,
  DeliberationAttemptDto,
  DeliberationManifestDto,
  DeliberationRoomDetailDto,
  DeliberationRoomSummaryDto,
  PreparedDeliberationDto,
  PreparedDeliberationRetryDto,
  WorkspacePage,
} from "../../api/dto.js";
import type { ProjectRoute } from "../../routing/project-route.js";
import type { InspectorSelection } from "./ContextInspector.js";
import { Button } from "../primitives/Button.js";
import { StatusBadge } from "../primitives/StatusBadge.js";
import { WorkspaceHeader } from "./WorkspaceHeader.js";

interface Props {
  readonly language: AppLanguage;
  readonly projectId: string;
  readonly route: ProjectRoute;
  readonly onNavigate: (href: string) => void;
  readonly onInspect: (selection: InspectorSelection) => void;
  readonly onError: (error: unknown) => void;
  readonly onNotice: (message: string, tone?: "ready" | "warning" | "danger") => void;
  readonly onAuthorityChanged: () => Promise<void>;
}

const RESOLUTIONS = ["adopt_a", "adopt_b", "combine_edit", "keep_disputed", "request_evidence", "close_without_change"] as const;

function c(language: AppLanguage, en: string, zh: string): string { return language === "en" ? en : zh; }
function date(language: AppLanguage, value: string): string { try { return new Intl.DateTimeFormat(language, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); } catch { return value; } }
function values(value: FormDataEntryValue | null): readonly string[] { return typeof value === "string" ? value.split(/[\r\n,]+/u).map((item) => item.trim()).filter(Boolean) : []; }
function text(value: FormDataEntryValue | null): string { return typeof value === "string" ? value.trim() : ""; }
function tone(status: string): "ready" | "working" | "warning" | "danger" | "neutral" {
  if (["resolved", "closed", "difference_review", "waiting_user_resolution"].includes(status)) return "ready";
  if (["blind_round_running", "challenge_running", "retry_running", "context_prepared"].includes(status)) return "working";
  if (["failed", "stale_conflicted"].includes(status)) return "danger";
  if (["partial", "cancelled", "reveal_ready", "awaiting_manifest_confirmation", "challenge_prepared", "retry_prepared"].includes(status)) return "warning";
  return "neutral";
}

export function DeliberationRoomWorkspace(props: Props) {
  if (props.route.creating) return <CreateRoom {...props} />;
  if (props.route.objectId) return <RoomDetail {...props} roomId={props.route.objectId} />;
  return <RoomLedger {...props} />;
}

function CreateRoom(props: Props) {
  const params = new URLSearchParams(window.location.search);
  const requestedSourceKind = params.get("sourceKind");
  const sourceKind = requestedSourceKind === "correction_appeal" || requestedSourceKind === "research_decision" || requestedSourceKind === "research_brief" || requestedSourceKind === "research_object" ? requestedSourceKind : "research_issue";
  const sourceObjectId = params.get("source") ?? "";
  const initialQuestion = params.get("question") ?? "";
  const initialTitle = params.get("title") ?? c(props.language, "Two-view deliberation", "双视角会商");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  async function submit(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault(); setError(undefined);
    const data = new FormData(event.currentTarget);
    const question = text(data.get("question")); const title = text(data.get("title"));
    if (!sourceObjectId || !question || !title) { setError(c(props.language, "A legal source, Frozen Question, and title are required.", "必须提供合法来源、冻结问题和标题。")); return; }
    setBusy(true);
    try {
      const room = await researchRoomApi.createDeliberationRoom({ projectId: props.projectId, sourceKind, sourceObjectId, question, title });
      props.onNotice(c(props.language, "Deliberation draft created. No Provider call has been made.", "会商草稿已创建，尚未调用任何 Provider。"), "ready");
      props.onNavigate(`/project/deliberation-rooms/${room.id}${params.get("revision") ? `?revision=${encodeURIComponent(params.get("revision") ?? "")}` : ""}`);
    } catch (caught) { props.onError(caught); }
    finally { setBusy(false); }
  }
  return <section className="object-workspace deliberation-workspace" aria-labelledby="deliberation-create-title">
      <WorkspaceHeader id="deliberation-create-title" eyebrow="BLIND PARALLEL · 2 PARTICIPANTS" className="deliberation-hero" title={c(props.language, "Create a bounded Deliberation Room", "创建有限轮次会商室")} description={c(props.language, "Freeze one project-bound question. Two exact requests will be inspected before either is sent; no participant, synthesis model, or agreement can resolve the Room for you.", "冻结一个项目内问题。两份精确请求会在发送前供你检查；参与者、综合模型或一致意见都不能替你裁决。")} actions={<Button type="button" variant="quiet" onClick={() => { props.onNavigate(`/project/${sourceKind === "correction_appeal" ? "appeals" : sourceKind === "research_decision" ? "decisions" : "issues"}/${sourceObjectId}`); }}>{c(props.language, "Back to source", "返回来源")}</Button>} />
    <section className="deliberation-source-lock"><StatusBadge tone="warning">{c(props.language, "Frozen on create", "创建时冻结")}</StatusBadge><dl><dt>{c(props.language, "Source", "来源")}</dt><dd>{sourceKind} · <code>{sourceObjectId || "missing"}</code></dd><dt>{c(props.language, "Authority", "权威")}</dt><dd>{c(props.language, "Direct user command only", "仅直接用户命令")}</dd></dl></section>
    <form className="structured-editor deliberation-create-form" onSubmit={(event) => { void submit(event); }}>
      <label>{c(props.language, "Room title", "会商标题")}<input name="title" required maxLength={512} defaultValue={initialTitle} /></label>
      <label>{c(props.language, "Frozen Question", "冻结问题")}<textarea name="question" required maxLength={16384} defaultValue={initialQuestion} placeholder={c(props.language, "State the exact research dispute without asking for a winner.", "准确写明研究争点，不要要求模型选赢家。")}/></label>
      <div className="deliberation-rule-strip"><span>2 {c(props.language, "participants", "位参与者")}</span><span>1 {c(props.language, "blind round", "轮互盲首答")}</span><span>≤ 1 {c(props.language, "directed challenge", "轮定向回应")}</span><span>0 {c(props.language, "automatic retries", "次自动重试")}</span></div>
      {error ? <p className="inline-error" role="alert">{error}</p> : null}
      <Button type="submit" variant="primary" disabled={busy}>{busy ? c(props.language, "Freezing…", "正在冻结……") : c(props.language, "Create durable draft", "创建持久草稿")}</Button>
    </form>
  </section>;
}

function RoomLedger(props: Props) {
  const [page, setPage] = useState<WorkspacePage<DeliberationRoomSummaryDto>>();
  const [loading, setLoading] = useState(true);
  const [status, setStatus] = useState("");
  async function load() { setLoading(true); try { setPage(await researchRoomApi.listResearchObjects("deliberation_room", { limit: 50, ...(status ? { status } : {}) }) as WorkspacePage<DeliberationRoomSummaryDto>); } catch (error) { props.onError(error); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [props.projectId, status]);
  return <section className="object-workspace deliberation-workspace" aria-labelledby="deliberation-ledger-title"><WorkspaceHeader id="deliberation-ledger-title" eyebrow="PROJECT HISTORY" className="deliberation-hero" title={c(props.language, "Deliberation Rooms", "会商室记录")} description={c(props.language, "Project-bound rooms remain searchable with their failures, minority views, user resolutions, and receipts.", "项目内会商会保留失败、少数意见、用户裁决和凭证，并可继续搜索。")} actions={<Button type="button" variant="quiet" disabled={loading} onClick={() => { void load(); }}>{c(props.language, "Refresh", "刷新")}</Button>} /><label className="ledger-inline-filter">{c(props.language, "Status", "状态")}<select value={status} onChange={(event) => { setStatus(event.target.value); }}><option value="">{c(props.language, "All", "全部")}</option>{["draft", "blind_round_running", "reveal_ready", "difference_review", "partial", "failed", "waiting_user_resolution", "resolved", "closed"].map((item) => <option key={item}>{item}</option>)}</select></label>{page?.items.length ? <ol className="structured-list ledger-list deliberation-ledger">{page.items.map((room) => <li key={room.id}><button type="button" onClick={() => { props.onNavigate(`/project/deliberation-rooms/${room.id}`); }}><span><strong>{room.title}</strong><small>{room.source.kind} · {room.providerCallCount}/{room.providerCallLimit} calls · {date(props.language, room.updatedAt)}</small></span><StatusBadge tone={tone(room.status)}>{room.status}</StatusBadge></button></li>)}</ol> : !loading ? <div className="empty-state"><strong>{c(props.language, "No Deliberation Room is recorded.", "尚未记录会商室。")}</strong><p>{c(props.language, "Start from an eligible Issue or Correction Appeal. Empty projects do not gain a permanent navigation section.", "请从符合条件的 Issue 或纠错申诉发起；空项目不会增加永久导航区域。")}</p><Button type="button" variant="quiet" onClick={() => { props.onNavigate("/project/issues"); }}>{c(props.language, "Open Issues", "打开 Issues")}</Button></div> : <p className="empty-state" role="status">{c(props.language, "Reading local rooms…", "正在读取本地会商室……")}</p>}</section>;
}

function RoomDetail(props: Props & { readonly roomId: string }) {
  const [detail, setDetail] = useState<DeliberationRoomDetailDto>();
  const [prepared, setPrepared] = useState<PreparedDeliberationDto>();
  const [preparedRetry, setPreparedRetry] = useState<PreparedDeliberationRetryDto>();
  const [busy, setBusy] = useState(false);
  const [acknowledged, setAcknowledged] = useState(false);
  const [loading, setLoading] = useState(true);
  const pollRef = useRef<number | undefined>(undefined);
  async function load(silent = false) { if (!silent) setLoading(true); try { setDetail(await researchRoomApi.researchObject("deliberation_room", props.roomId) as DeliberationRoomDetailDto); } catch (error) { if (!silent) props.onError(error); } finally { if (!silent) setLoading(false); } }
  useEffect(() => { setPrepared(undefined); setPreparedRetry(undefined); setAcknowledged(false); void load(); return () => { if (pollRef.current !== undefined) window.clearInterval(pollRef.current); }; }, [props.projectId, props.roomId]);
  useEffect(() => {
    if (!detail || !["blind_round_running", "challenge_running", "retry_running"].includes(detail.status)) { if (pollRef.current !== undefined) { window.clearInterval(pollRef.current); pollRef.current = undefined; } return; }
    pollRef.current ??= window.setInterval(() => { void load(true); }, 700);
    return () => { if (pollRef.current !== undefined) { window.clearInterval(pollRef.current); pollRef.current = undefined; } };
  }, [detail?.status, props.roomId]);
  async function mutate(action: () => Promise<DeliberationRoomDetailDto>, notice: string, authority = false) {
    setBusy(true);
    try { const next = await action(); setDetail(next); setPrepared(undefined); setPreparedRetry(undefined); setAcknowledged(false); props.onNotice(notice, "ready"); if (authority) await props.onAuthorityChanged(); }
    catch (error) { props.onError(error); }
    finally { setBusy(false); }
  }
  async function run(action: () => Promise<DeliberationRoomDetailDto>, notice: string) {
    setBusy(true); window.setTimeout(() => { void load(true); }, 80);
    try { const next = await action(); setDetail(next); setPrepared(undefined); setPreparedRetry(undefined); setAcknowledged(false); props.onNotice(notice, next.status === "failed" || next.status === "partial" ? "warning" : "ready"); }
    catch (error) { props.onError(error); await load(true); }
    finally { setBusy(false); }
  }
  if (!detail) return <section className="object-workspace deliberation-workspace"><p className="empty-state" role="status">{loading ? c(props.language, "Reading the local Room…", "正在读取本地会商室……") : c(props.language, "Deliberation Room not found.", "未找到会商室。")}</p></section>;
  const available = new Set(detail.availableActions);
  const challenge = detail.challenge;
  const retry = detail.retry;
  const manifestPair = detail.status === "challenge_prepared" ? challenge?.manifests : detail.manifests;
  const assessments = detail.assessments.filter((attempt) => attempt.assessment !== undefined);
  const failed = detail.participantStates.filter((participant) => ["failed", "cancelled", "unknown"].includes(participant.status));
  return <section className="object-workspace deliberation-workspace" aria-labelledby="deliberation-room-title">
      <WorkspaceHeader id="deliberation-room-title" eyebrow="DELIBERATION ROOM · BLIND PARALLEL" className="deliberation-room-header" title={detail.title} description={<span className="frozen-question"><span>{c(props.language, "Frozen Question", "冻结问题")}</span>{detail.source.question}</span>} status={<StatusBadge tone={tone(detail.status)}>{detail.status}</StatusBadge>} actions={<><Button type="button" variant="secondary" disabled={busy} onClick={() => { props.onNavigate(`/project/memory?pinKind=deliberation_room&pinId=${encodeURIComponent(detail.id)}`); }}>{c(props.language, "Pin to Project Memory", "固定到项目记忆")}</Button><Button type="button" variant="quiet" data-inspector-return="research_object" onClick={() => { props.onInspect({ kind: "research_object", title: detail.title, status: detail.status, fields: [{ label: "Room ID", value: detail.id }, { label: c(props.language, "Source binding", "来源绑定"), value: `${detail.source.kind}:${detail.source.objectId}@${detail.source.objectVersion}` }, { label: "Source hash", value: detail.source.sourceHash }, { label: c(props.language, "Authority", "权威"), value: c(props.language, "user only; no automatic canonical mutation", "仅用户；不会自动修改权威研究状态") }, { label: c(props.language, "Calls", "调用"), value: `${detail.providerCallCount}/${detail.providerCallLimit}` }], relations: [{ label: c(props.language, "Open source", "打开来源"), href: detail.sourceHref }, ...detail.receiptHrefs.map((href, index) => ({ label: `Receipt ${index + 1}`, href }))] }); }}>{c(props.language, "Inspector", "检查器")}</Button></>} />
    <section className="deliberation-protocol-bar" aria-label={c(props.language, "Protocol status", "协议状态")}><div><strong>blind_parallel</strong><span>{c(props.language, "Requests frozen before dispatch", "请求在发送前冻结")}</span></div><div><strong>{detail.providerCallCount} / {detail.providerCallLimit}</strong><span>{c(props.language, "Provider calls", "Provider 调用")}</span></div><div><strong>{detail.participants.length}</strong><span>{c(props.language, "fixed participants", "固定参与者")}</span></div><div><strong>{detail.challenge ? "1 / 1" : "0 / 1"}</strong><span>{c(props.language, "directed challenge", "定向回应")}</span></div></section>
    <section className="deliberation-independence" data-ready={detail.providerReadiness === "configured_distinct"}><div><StatusBadge tone={detail.providerReadiness === "configured_distinct" ? "ready" : "warning"}>{detail.providerReadiness}</StatusBadge><strong>{detail.providerReadiness === "configured_distinct" ? c(props.language, "Runtime identities are distinct", "运行身份彼此不同") : c(props.language, "Mutually blind two-participant run is blocked", "互盲双参与者运行已阻止")}</strong><p>{c(props.language, "Protocol isolation is enforced; mutual cognitive independence remains unproven.", "协议隔离已执行；相互认知独立性仍为 unproven。")}</p></div><div className="participant-binding-grid">{detail.participants.map((participant, index) => <article key={participant.id}><span className="participant-letter">{participant.slot.toUpperCase()}</span><div><strong>{participant.providerId} · {participant.model}</strong><small>{participant.locality} · config {participant.configGeneration} · {participant.harnessId}</small><StatusBadge tone={tone(detail.participantStates[index]?.status ?? "ready")}>{detail.participantStates[index]?.status ?? "ready"}</StatusBadge></div></article>)}</div></section>

    {detail.status === "draft" ? <DraftConfiguration language={props.language} detail={detail} busy={busy} onPrepare={async (input) => {
      setBusy(true); try { const next = await researchRoomApi.prepareDeliberationRoom({ projectId: props.projectId, roomId: detail.id, expectedVersion: detail.version, ...input }); setPrepared(next); setDetail(next.room); setAcknowledged(false); props.onNotice(c(props.language, "Both exact Manifests are ready. Nothing has been sent.", "两份精确 Manifest 已准备完成，尚未发送。"), "ready"); } catch (error) { props.onError(error); } finally { setBusy(false); }
    }} onManual={() => { document.getElementById("manual-opinion-form")?.scrollIntoView({ behavior: "smooth", block: "start" }); }} /> : null}

    {(detail.status === "awaiting_manifest_confirmation" || detail.status === "challenge_prepared") && manifestPair ? <section className="deliberation-stage manifest-stage" aria-labelledby="manifest-stage-title"><StageHeading number={detail.status === "challenge_prepared" ? "05" : "03"} title={detail.status === "challenge_prepared" ? c(props.language, "Directed challenge Manifests", "定向回应 Manifest") : c(props.language, "Inspect both Context Manifests", "检查两份 Context Manifest")} description={c(props.language, "These hashes bind the exact permitted context. Confirmation starts only the displayed calls; raw bodies and secrets are never rendered.", "这些 hash 绑定准确的允许上下文。确认后只启动所示调用；原始网络载荷和密钥永不渲染。")}/><div className="manifest-pair">{manifestPair.map((manifest, index) => <ManifestCard key={manifest.canonicalHash} language={props.language} manifest={manifest} preview={prepared?.providerPreviews[index]} />)}</div><label className="authority-confirm"><input type="checkbox" checked={acknowledged} onChange={(event) => { setAcknowledged(event.target.checked); }}/><span>{c(props.language, "I inspected both Manifests and explicitly authorize these bounded sends.", "我已检查两份 Manifest，并明确授权这些有限发送。")}</span></label><div className="stage-actions"><Button type="button" variant="primary" disabled={busy || !acknowledged} onClick={() => { if (detail.status === "challenge_prepared" && challenge) void run(() => researchRoomApi.runDeliberationChallenge(props.projectId, detail.id, detail.version, challenge.id, manifestPair.map((item) => item.canonicalHash) as [string, string]), c(props.language, "Directed challenge reached a terminal state.", "定向回应已到达终态。")); else void run(() => researchRoomApi.runDeliberationRoom(props.projectId, detail.id, detail.version, manifestPair.map((item) => item.canonicalHash) as [string, string]), c(props.language, "Blind initial round reached a terminal state.", "互盲首轮已到达终态。")); }}>{detail.status === "challenge_prepared" ? c(props.language, "Start one directed challenge", "启动一次定向回应") : c(props.language, "Start blind initial round", "启动互盲首轮")}</Button></div></section> : null}

    {detail.status === "retry_prepared" && retry ? <section className="deliberation-stage manifest-stage"><StageHeading number="R" title={c(props.language, "Fresh Manifest for the failed participant", "失败参与者的新 Manifest")} description={c(props.language, "Only the failed participant is called. The completed assessment stays append-only and is not silently rerun.", "只调用失败参与者；已完成的 assessment 按追加方式保留，不会被静默重跑。")}/><ManifestCard language={props.language} manifest={retry.manifest} preview={preparedRetry?.providerPreview}/><label className="authority-confirm"><input type="checkbox" checked={acknowledged} onChange={(event) => { setAcknowledged(event.target.checked); }}/><span>{c(props.language, "I confirm this one extra call. It consumes the remaining budget and disables the two-call challenge.", "我确认这一次额外调用；它占用剩余预算，并禁用需要两次调用的 challenge。")}</span></label><Button type="button" variant="primary" disabled={busy || !acknowledged} onClick={() => { void run(() => researchRoomApi.runDeliberationRetry(props.projectId, detail.id, detail.version, retry.id, retry.manifest.canonicalHash), c(props.language, "The explicit retry reached a terminal state.", "显式重试已到达终态。")); }}>{c(props.language, "Retry failed participant", "重试失败参与者")}</Button></section> : null}

    {["blind_round_running", "challenge_running", "retry_running"].includes(detail.status) ? <section className="deliberation-stage running-stage" aria-live="polite"><StageHeading number="04" title={detail.status === "challenge_running" ? c(props.language, "Directed challenge running", "定向回应运行中") : detail.status === "retry_running" ? c(props.language, "Explicit retry running", "显式重试运行中") : c(props.language, "Mutually blind initial round", "互盲首轮运行中")} description={c(props.language, "Only safe terminal states are visible. A participant finishing first cannot change the peer request that was already frozen.", "这里只显示安全终态；一方先完成也无法改变对方已经冻结的请求。")}/><div className="blind-running-grid">{detail.participantStates.map((participant) => <article key={participant.slot}><span className="participant-letter">{participant.slot.toUpperCase()}</span><div><strong>{participant.providerId}</strong><StatusBadge tone={tone(participant.status)}>{participant.status}</StatusBadge><small>{c(props.language, "No streaming answer · no hidden reasoning", "不显示流式答案 · 不显示隐藏推理")}</small></div></article>)}</div>{available.has("cancel") ? <Button type="button" variant="danger" disabled={false} onClick={() => { void mutate(() => researchRoomApi.cancelDeliberationRun(props.projectId, detail.id, detail.version), c(props.language, "Cancellation requested. Completed results remain sealed until you explicitly reveal them.", "已请求取消；已完成结果会继续封存，直到你明确解盲。")); }}>{c(props.language, "Cancel bounded run", "取消有限运行")}</Button> : null}</section> : null}

    {detail.status === "reveal_ready" ? <section className="deliberation-stage reveal-stage"><StageHeading number="04" title={c(props.language, "Terminal results are sealed", "终态结果仍处于封存状态")} description={available.has("reveal_complete") ? c(props.language, "Both legal assessments are terminal. Reveal them together to derive the deterministic Difference Summary.", "两份合法 assessment 均已终止；一起解盲后由 Kernel 确定性生成 Difference Summary。") : c(props.language, "Only one legal assessment exists. You may explicitly view that partial result; no complete two-participant Difference Summary will be claimed.", "只有一份合法 assessment；你可以明确查看 partial，但不会声称生成完整双参与者 Difference Summary。")}/><Button type="button" variant="primary" disabled={busy} onClick={() => { const mode = available.has("reveal_complete") ? "complete" : detail.participantStates.some((item) => item.status === "cancelled") ? "cancelled" : "partial"; void mutate(() => researchRoomApi.revealDeliberationRoom(props.projectId, detail.id, detail.version, mode), c(props.language, "The user-confirmed reveal was recorded.", "用户确认的解盲已记录。")); }}>{available.has("reveal_complete") ? c(props.language, "Reveal both assessments", "解盲两份 assessment") : c(props.language, "View legal partial result", "查看合法 partial 结果")}</Button></section> : null}

    {detail.differenceSummary ? <DifferenceReview language={props.language} detail={detail} assessments={assessments} /> : null}

    {detail.status === "difference_review" && available.has("prepare_challenge") ? <ChallengeForm language={props.language} busy={busy} onSubmit={async (question) => { setBusy(true); try { const next = await researchRoomApi.prepareDeliberationChallenge(props.projectId, detail.id, detail.version, question); setPrepared(next); setDetail(next.room); setAcknowledged(false); } catch (error) { props.onError(error); } finally { setBusy(false); } }} onFinish={() => { void mutate(() => researchRoomApi.finishDeliberationReview(props.projectId, detail.id, detail.version), c(props.language, "Difference review closed; your Resolution is now required.", "差异复核已结束；现在需要你的 Resolution。")); }} /> : null}
    {detail.status === "difference_review" && !available.has("prepare_challenge") && available.has("finish_review") ? <div className="stage-actions"><Button type="button" variant="primary" disabled={busy} onClick={() => { void mutate(() => researchRoomApi.finishDeliberationReview(props.projectId, detail.id, detail.version), c(props.language, "Your Resolution is now required.", "现在需要你的 Resolution。")); }}>{c(props.language, "Continue to Resolution", "继续到 Resolution")}</Button></div> : null}

    {["partial", "failed", "cancelled", "stale_conflicted"].includes(detail.status) ? <FailurePanel language={props.language} detail={detail} failed={failed} busy={busy} onRetry={available.has("prepare_retry") ? async () => { setBusy(true); try { const next = await researchRoomApi.prepareDeliberationRetry(props.projectId, detail.id, detail.version); setPreparedRetry(next); setDetail(next.room); setAcknowledged(false); } catch (error) { props.onError(error); } finally { setBusy(false); } } : undefined} onResolve={() => { document.getElementById("deliberation-resolution")?.scrollIntoView({ behavior: "smooth", block: "start" }); }} /> : null}

    {detail.status !== "closed" ? <ManualOpinionForm language={props.language} detail={detail} busy={busy} onSubmit={(input) => mutate(() => researchRoomApi.importManualDeliberationOpinion({ projectId: props.projectId, roomId: detail.id, expectedVersion: detail.version, ...input }), c(props.language, "Manual external opinion appended as non-blind and unverified.", "手工外部意见已按非互盲、未验证记录追加。"))} /> : null}

    {available.has("resolve") ? <ResolutionForm language={props.language} detail={detail} busy={busy} onSubmit={(input) => mutate(() => researchRoomApi.resolveDeliberationRoom({ projectId: props.projectId, roomId: detail.id, expectedVersion: detail.version, ...input }), c(props.language, "Your superseding Room Resolution and receipt were appended. Canonical research objects were not changed.", "你的 Room Resolution 与凭证已按追加方式记录；权威研究对象未被自动修改。"), true)} /> : null}
    {!available.has("resolve") && available.has("close") && !["blind_round_running", "challenge_running", "retry_running"].includes(detail.status) ? <CloseRoomForm language={props.language} detail={detail} busy={busy} onSubmit={(publicReason) => mutate(() => researchRoomApi.resolveDeliberationRoom({ projectId: props.projectId, roomId: detail.id, expectedVersion: detail.version, kind: "close_without_change", publicReason }), c(props.language, "The Room was closed without changing canonical research state.", "Room 已关闭，权威研究状态未被修改。"), true)} /> : null}

    <section className="deliberation-trace" aria-labelledby="deliberation-trace-title"><div className="workspace-section-header"><div><p className="eyebrow">RECEIPT / TRACE</p><h2 id="deliberation-trace-title">{c(props.language, "Append-only room history", "追加式会商历史")}</h2></div><Button type="button" variant="quiet" onClick={() => { void load(); }}>{c(props.language, "Refresh", "刷新")}</Button></div><ol>{detail.trace.map((entry, index) => <li key={`${entry.step}-${entry.at}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{entry.step}</strong><p>{entry.summary}</p><small>{date(props.language, entry.at)}</small></div></li>)}</ol>{detail.resolutions.map((resolution, index) => <details key={`resolution-${index}`}><summary>{c(props.language, "User Resolution receipt", "用户 Resolution 凭证")} {index + 1}</summary><pre>{JSON.stringify(resolution, null, 2)}</pre></details>)}</section>
  </section>;
}

function StageHeading({ number, title, description }: { readonly number: string; readonly title: string; readonly description: string }) { return <header className="stage-heading"><span>{number}</span><div><h2>{title}</h2><p>{description}</p></div></header>; }

function DraftConfiguration({ language, detail, busy, onPrepare, onManual }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly busy: boolean; readonly onPrepare: (input: { readonly revisionId: string; readonly decisionIds: readonly string[]; readonly issueIds: readonly string[]; readonly evidenceIds: readonly string[] }) => Promise<void>; readonly onManual: () => void }) {
  const params = new URLSearchParams(window.location.search);
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await onPrepare({ revisionId: text(data.get("revisionId")), decisionIds: values(data.get("decisionIds")), issueIds: values(data.get("issueIds")), evidenceIds: values(data.get("evidenceIds")) }); }
  return <section className="deliberation-stage context-stage"><StageHeading number="02" title={c(language, "Freeze evidence boundaries", "冻结证据边界")} description={c(language, "The current Brief is always included. Add only project-local Decisions, Issues, Evidence, and one exact source revision.", "当前 Brief 始终包含；这里只加入项目内 Decision、Issue、Evidence 与一个精确来源 revision。")}/>{detail.providerReadiness !== "configured_distinct" ? <div className="provider-blocked"><StatusBadge tone="warning">{detail.providerReadiness}</StatusBadge><h3>{c(language, "The two-participant run cannot start", "双参与者运行无法启动")}</h3><p>{detail.providerReadiness === "blocked_missing_provider" ? c(language, "Two Provider connections are not configured. The durable Room and manual external-opinion path remain available.", "尚未配置两条 Provider 连接；持久 Room 与手工外部意见路径仍可使用。") : c(language, "The selected connections share a runtime identity. Sestina will not label them mutually independent.", "所选连接共享运行身份；Sestina 不会将其标记为相互独立。")}</p><Button type="button" variant="quiet" onClick={onManual}>{c(language, "Use manual external opinion", "使用手工外部意见")}</Button></div> : <form className="structured-editor context-selection-form" onSubmit={(event) => { void submit(event); }}><label>{c(language, "Exact source revision ID", "精确来源 revision ID")}<input name="revisionId" required pattern="rrev_[0-9A-HJKMNP-TV-Z]{26}" defaultValue={params.get("revision") ?? ""}/></label><div className="field-grid"><label>{c(language, "Retained Decision IDs", "保留的 Decision ID")}<textarea name="decisionIds" placeholder="rdec_…" /></label><label>{c(language, "Allowed Issue IDs", "允许的 Issue ID")}<textarea name="issueIds" defaultValue={detail.source.kind === "research_issue" ? detail.source.objectId : ""} placeholder="riss_…" /></label><label>{c(language, "Allowed Evidence IDs", "允许的 Evidence ID")}<textarea name="evidenceIds" placeholder="revd_…" /></label></div><p className="context-safety-note">{c(language, "Excluded by protocol: peer output, peer session/private context, raw Provider responses, secrets, authentication headers, hidden chain of thought.", "协议排除：对方输出、对方 session/私有上下文、Provider 原始响应、密钥、认证头和隐藏思维链。")}</p><Button type="submit" variant="primary" disabled={busy}>{c(language, "Build two exact Manifests", "生成两份精确 Manifest")}</Button></form>}</section>;
}

function ManifestCard({ language, manifest, preview }: { readonly language: AppLanguage; readonly manifest: DeliberationManifestDto; readonly preview?: PreparedDeliberationDto["providerPreviews"][number] | PreparedDeliberationRetryDto["providerPreview"] }) {
  return <article className="manifest-card"><header><span className="participant-letter">{manifest.participantSlot.toUpperCase()}</span><div><strong>Context Manifest</strong><small>{manifest.participantId}</small></div><StatusBadge tone="ready">{c(language, "unsent", "未发送")}</StatusBadge></header><dl><dt>{c(language, "Canonical hash", "规范 hash")}</dt><dd><code>{manifest.canonicalHash}</code></dd><dt>{c(language, "Request binding", "请求绑定")}</dt><dd><code>{manifest.requestHash}</code></dd><dt>{c(language, "State binding", "状态绑定")}</dt><dd><code>{manifest.stateBindingHash}</code></dd><dt>{c(language, "Included objects", "包含对象")}</dt><dd>{manifest.includedObjects.length} · {manifest.includedFields.join(" · ")}</dd><dt>{c(language, "Excluded fields", "排除字段")}</dt><dd>{manifest.excludedFields.join(" · ")}</dd><dt>{c(language, "Budget", "预算")}</dt><dd>{manifest.tokenBudget} tokens · {manifest.maxResponseBytes} bytes · tools={manifest.tools}</dd><dt>{c(language, "Transport preview", "传输预览")}</dt><dd>{preview ? `${preview.endpoint} · ${preview.requestBodyBytes} bytes · retry=${preview.retryCount}` : c(language, "Rebuilt locally from the persisted Manifest when confirmed", "确认时由持久 Manifest 在本地重建")}</dd></dl></article>;
}

function DifferenceReview({ language, detail, assessments }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly assessments: readonly DeliberationAttemptDto[] }) {
  const summary = detail.differenceSummary;
  if (!summary) return null;
  return <section className="deliberation-stage difference-stage" aria-labelledby="difference-review-title"><StageHeading number="05" title={c(language, "Difference Summary first", "先看 Difference Summary")} description={detail.status === "partial" ? c(language, "This is a partial, explicitly revealed record—not a complete two-participant comparison.", "这是明确解盲的 partial 记录，不是完整双参与者比较。") : c(language, "Kernel-derived from normalized assessments and frozen dimensions. No winner, ranking, score, or synthesis Provider exists.", "由 Kernel 根据规范化 assessment 与冻结维度确定性生成；不存在赢家、排名、分数或综合 Provider。")}/><div className="difference-category-grid">{summary.categories.filter((category) => category.status !== "absent").map((category) => <article key={category.kind} data-status={category.status}><header><strong>{category.kind.replaceAll("_", " ")}</strong><StatusBadge tone={category.status === "present" ? "warning" : "neutral"}>{category.status}</StatusBadge></header>{category.statements.length ? <ul>{category.statements.map((statement) => <li key={statement}>{statement}</li>)}</ul> : <p>—</p>}</article>)}</div><div className="difference-safety"><span>{c(language, "winner", "赢家")}: <b>none</b></span><span>{c(language, "ranking", "排名")}: <b>none</b></span><span>{c(language, "score", "分数")}: <b>none</b></span><span>{c(language, "authority", "权威")}: <b>system_derived / cannot resolve</b></span></div><h3>{c(language, "Participant assessments", "参与者 assessment")}</h3><div className="assessment-stack">{assessments.map((attempt) => <AssessmentCard key={attempt.id} language={language} attempt={attempt}/>)}</div></section>;
}

function AssessmentCard({ language, attempt }: { readonly language: AppLanguage; readonly attempt: DeliberationAttemptDto }) {
  const assessment = attempt.assessment;
  if (!assessment) return null;
  return <details className="assessment-card"><summary><span className="participant-letter">{assessment.participantSlot.toUpperCase()}</span><span><strong>{assessment.assessment}</strong><small>{assessment.directAnswer}</small></span><StatusBadge tone="neutral">{attempt.status}</StatusBadge></summary><div><h4>{c(language, "Public rationale", "公开理由")}</h4><p>{assessment.publicRationale}</p><h4>{c(language, "Assumptions and scope", "假设与范围")}</h4><p>{assessment.assumptions.join(" · ") || "—"}</p><p><b>{c(language, "Scope", "范围")}:</b> {assessment.scope}</p><h4>{c(language, "Alternative explanations", "替代解释")}</h4><p>{assessment.alternativeExplanations.join(" · ") || "—"}</p><h4>{c(language, "Unknowns / missing context", "未知项 / 缺失上下文")}</h4><p>{[...assessment.unknowns, ...assessment.missingContext].join(" · ") || "—"}</p><h4>{c(language, "Next discriminating evidence", "下一项区分性证据")}</h4><p>{assessment.nextDiscriminatingEvidence.join(" · ") || "—"}</p><h4>{c(language, "Proposed next step", "建议下一步")}</h4><p>{assessment.proposedNextStep}</p></div></details>;
}

function ChallengeForm({ language, busy, onSubmit, onFinish }: { readonly language: AppLanguage; readonly busy: boolean; readonly onSubmit: (question: string) => Promise<void>; readonly onFinish: () => void }) {
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const question = text(new FormData(event.currentTarget).get("challenge")); if (question) await onSubmit(question); }
  return <section className="deliberation-stage challenge-stage"><StageHeading number="06" title={c(language, "Optional one-round directed challenge", "可选的一轮定向回应")} description={c(language, "Each participant receives only the user-confirmed room-shared Difference Summary and the peer's public structured assessment. This makes two final calls; no fifth call follows.", "每位参与者只收到用户确认的 room-shared Difference Summary 与对方公开结构化 assessment。这是最后两次调用，之后没有第五次调用。")}/><form className="structured-editor" onSubmit={(event) => { void submit(event); }}><label>{c(language, "One shared challenge question", "一个共享定向问题")}<textarea name="challenge" required maxLength={8192} defaultValue={c(language, "Which exact evidence would change your bounded conclusion, and what remains unresolved?", "哪一项精确证据会改变你的有限结论，仍有哪些问题未解决？")}/></label><div className="stage-actions"><Button type="submit" variant="primary" disabled={busy}>{c(language, "Prepare two challenge Manifests", "准备两份 challenge Manifest")}</Button><Button type="button" variant="quiet" disabled={busy} onClick={onFinish}>{c(language, "Skip challenge and resolve", "跳过 challenge 并裁决")}</Button></div></form></section>;
}

function FailurePanel({ language, detail, failed, busy, onRetry, onResolve }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly failed: readonly DeliberationRoomDetailDto["participantStates"][number][]; readonly busy: boolean; readonly onRetry?: () => Promise<void>; readonly onResolve: () => void }) {
  return <section className="deliberation-stage failure-stage" data-status={detail.status}><StageHeading number="!" title={detail.status === "partial" ? c(language, "Partial—not a completed deliberation", "Partial——并非完成的会商") : detail.status === "failed" ? c(language, "Both participant paths failed", "两条参与者路径均失败") : detail.status === "stale_conflicted" ? c(language, "Source changed; old confirmation is invalid", "来源已变化；旧确认已失效") : c(language, "Run cancelled", "运行已取消")} description={detail.status === "failed" ? c(language, "No Difference Summary was created. Frozen context and failure history remain durable; no research object was changed.", "未生成 Difference Summary；冻结上下文和失败历史仍会持久保留，研究对象没有被修改。") : c(language, "The successful assessment, failures, cancellation, and unknowns remain append-only. Sestina does not fabricate a fallback result.", "成功 assessment、失败、取消和未知项都会追加保留；Sestina 不会伪造 fallback 结果。")}/>{failed.length ? <ul className="failure-list">{failed.map((item) => <li key={item.slot}><span className="participant-letter">{item.slot.toUpperCase()}</span><strong>{item.providerId}</strong><StatusBadge tone="danger">{item.status}</StatusBadge></li>)}</ul> : null}<div className="stage-actions">{onRetry ? <Button type="button" variant="primary" disabled={busy} onClick={() => { void onRetry(); }}>{c(language, "Prepare fresh retry Manifest", "准备新的重试 Manifest")}</Button> : null}<Button type="button" variant="quiet" onClick={onResolve}>{c(language, "Record user Resolution", "记录用户 Resolution")}</Button></div></section>;
}

function ManualOpinionForm({ language, detail, busy, onSubmit }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly busy: boolean; readonly onSubmit: (input: { readonly sourceLabel: string; readonly providerClaim: string; readonly modelClaim: string; readonly capturedAt: string; readonly contextDisclosure: string; readonly sawParticipantAOutput: boolean; readonly sawParticipantBOutput: boolean; readonly publicContent: string }) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await onSubmit({ sourceLabel: text(data.get("sourceLabel")), providerClaim: text(data.get("providerClaim")), modelClaim: text(data.get("modelClaim")), capturedAt: new Date(text(data.get("capturedAt"))).toISOString(), contextDisclosure: text(data.get("contextDisclosure")), sawParticipantAOutput: data.get("sawA") === "on", sawParticipantBOutput: data.get("sawB") === "on", publicContent: text(data.get("publicContent")) }); form.reset(); setOpen(false); }
  return <section id="manual-opinion-form" className="deliberation-stage manual-opinion-stage"><header className="manual-opinion-header"><div><p className="eyebrow">MANUAL EXTERNAL OPINION</p><h2>{c(language, "Public candidate, never a blind participant", "公开候选意见，绝不冒充互盲参与者")}</h2><p>{c(language, "Paste only a public opinion you are authorized to record. Its source, capture time, context exposure, and non-verifiable blindness are preserved.", "只粘贴你有权记录的公开意见；来源、捕获时间、上下文暴露和不可验证互盲状态都会保留。")}</p></div><Button type="button" variant="quiet" onClick={() => { setOpen((value) => !value); }}>{open ? c(language, "Close form", "关闭表单") : c(language, "Add opinion", "添加意见")}</Button></header>{open ? <form className="structured-editor manual-opinion-form" onSubmit={(event) => { void submit(event); }}><div className="field-grid"><label>{c(language, "Source description", "来源描述")}<input name="sourceLabel" required maxLength={512}/></label><label>{c(language, "Claimed Provider", "声明的 Provider")}<input name="providerClaim" required maxLength={512}/></label><label>{c(language, "Claimed model", "声明的模型")}<input name="modelClaim" required maxLength={512}/></label><label>{c(language, "Captured at", "捕获时间")}<input name="capturedAt" type="datetime-local" required defaultValue={new Date().toISOString().slice(0, 16)}/></label></div><label>{c(language, "User-declared context scope", "用户声明的上下文范围")}<textarea name="contextDisclosure" required maxLength={8192}/></label><fieldset><legend>{c(language, "Output exposure", "输出暴露情况")}</legend><label><input type="checkbox" name="sawA"/> {c(language, "This opinion saw Participant A output", "该意见看过参与者 A 输出")}</label><label><input type="checkbox" name="sawB"/> {c(language, "This opinion saw Participant B output", "该意见看过参与者 B 输出")}</label></fieldset><label>{c(language, "Public opinion", "公开意见")}<textarea name="publicContent" required maxLength={32768}/></label><p className="inline-warning">manual_non_blind · unverified_external_import · blindness=not_verifiable · cannot resolve</p><Button type="submit" variant="primary" disabled={busy}>{c(language, "Append manual opinion", "追加手工意见")}</Button></form> : null}{detail.manualExternalOpinions.length ? <div className="manual-opinion-list">{detail.manualExternalOpinions.map((opinion) => <article key={opinion.id}><header><strong>{opinion.sourceLabel}</strong><StatusBadge tone="warning">{opinion.classification}</StatusBadge></header><p>{opinion.publicContent}</p><dl><dt>{c(language, "Captured", "捕获")}</dt><dd>{date(language, opinion.capturedAt)}</dd><dt>{c(language, "Context", "上下文")}</dt><dd>{opinion.contextDisclosure}</dd><dt>{c(language, "Saw A / B", "看过 A / B")}</dt><dd>{String(opinion.exposure.sawParticipantAOutput)} / {String(opinion.exposure.sawParticipantBOutput)}</dd><dt>{c(language, "Blindness", "互盲")}</dt><dd>{opinion.blindnessVerification}</dd></dl></article>)}</div> : null}</section>;
}

function ResolutionForm({ language, detail, busy, onSubmit }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly busy: boolean; readonly onSubmit: (input: { readonly kind: (typeof RESOLUTIONS)[number]; readonly publicReason: string; readonly combinedText?: string }) => Promise<void> }) {
  const [kind, setKind] = useState<(typeof RESOLUTIONS)[number]>("keep_disputed");
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await onSubmit({ kind, publicReason: text(data.get("publicReason")), ...(kind === "combine_edit" ? { combinedText: text(data.get("combinedText")) } : {}) }); }
  return <section id="deliberation-resolution" className="deliberation-stage resolution-stage"><StageHeading number="07" title={c(language, "Your Resolution", "你的 Resolution")} description={c(language, "Only this direct user command can resolve or close the Room. It appends a receipt but does not mutate the source Issue, Appeal, Decision, Brief, or Evidence.", "只有这条直接用户命令可以裁决或关闭 Room；它会追加凭证，但不会修改来源 Issue、Appeal、Decision、Brief 或 Evidence。")}/><form className="structured-editor" onSubmit={(event) => { void submit(event); }}><fieldset><legend>{c(language, "Disposition", "处置")}</legend><div className="resolution-choice-grid">{RESOLUTIONS.map((item) => <label key={item} data-selected={kind === item}><input type="radio" name="kind" value={item} checked={kind === item} onChange={() => { setKind(item); }}/><span><strong>{item.replaceAll("_", " ")}</strong><small>{item === "adopt_a" ? c(language, "Keep A as your Room conclusion", "将 A 作为你的 Room 结论") : item === "adopt_b" ? c(language, "Keep B as your Room conclusion", "将 B 作为你的 Room 结论") : item === "combine_edit" ? c(language, "Write your own bounded combined text", "写下你自己的有限合并文本") : item === "keep_disputed" ? c(language, "Preserve the disagreement", "保留分歧") : item === "request_evidence" ? c(language, "Require discriminating evidence", "要求区分性证据") : c(language, "Close without changing research state", "关闭且不修改研究状态")}</small></span></label>)}</div></fieldset>{kind === "combine_edit" ? <label>{c(language, "Your combined text", "你的合并文本")}<textarea name="combinedText" required maxLength={32768}/></label> : null}<label>{c(language, "Public reason", "公开理由")}<textarea name="publicReason" required maxLength={16384}/></label><div className="authority-gate"><strong>{c(language, "Authority Gate", "Authority Gate")}</strong><span>{c(language, `Room v${detail.version} · direct user confirmation · supersedes prior Room Resolution without overwriting it`, `Room v${detail.version} · 直接用户确认 · 追加取代旧 Room Resolution，不覆盖历史`)}</span></div><Button type="submit" variant={kind === "close_without_change" ? "secondary" : "primary"} disabled={busy}>{kind === "close_without_change" ? c(language, "Close Room without change", "关闭 Room 且不改动") : c(language, "Append my Resolution", "追加我的 Resolution")}</Button></form></section>;
}

function CloseRoomForm({ language, detail, busy, onSubmit }: { readonly language: AppLanguage; readonly detail: DeliberationRoomDetailDto; readonly busy: boolean; readonly onSubmit: (publicReason: string) => Promise<void> }) {
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const publicReason = text(new FormData(event.currentTarget).get("publicReason")); if (publicReason) await onSubmit(publicReason); }
  return <section className="deliberation-stage close-room-stage"><StageHeading number="×" title={c(language, "Close without changing research state", "关闭且不改变研究状态")} description={c(language, "This direct user action closes only this Room. It does not adopt either participant, alter the source object, or erase the append-only history.", "这条直接用户操作只关闭当前 Room；不会采纳任一参与者、修改来源对象或删除追加式历史。")}/><form className="structured-editor" onSubmit={(event) => { void submit(event); }}><label>{c(language, "Public reason", "公开理由")}<textarea name="publicReason" required maxLength={16384}/></label><div className="authority-gate"><strong>{c(language, "Authority Gate", "Authority Gate")}</strong><span>{c(language, `Room v${detail.version} · close_without_change · direct user confirmation`, `Room v${detail.version} · close_without_change · 直接用户确认`)}</span></div><Button type="submit" variant="secondary" disabled={busy}>{c(language, "Close Room without change", "关闭 Room 且不改动")}</Button></form></section>;
}
