import { useCallback, useEffect, useRef, useState, type SyntheticEvent } from "react";
import { researchRoomApi } from "../../api/client.js";
import type {
  AttentionDto,
  AppLanguage,
  BriefCandidateDto,
  BriefVersionDto,
  BriefWorkspaceDto,
  DecisionDetailDto,
  DecisionSummaryDto,
  EvidenceDetailDto,
  EvidenceSummaryDto,
  EpisodeDetailDto,
  EpisodeSummaryDto,
  IssueDetailDto,
  IssueSummaryDto,
  ObjectReceiptDetailDto,
  ObjectReceiptSummaryDto,
  ProjectOverviewDto,
  ResearchObjectKind,
  WorkspaceListRequest,
  WorkspacePage,
} from "../../api/dto.js";
import type { ProjectRoute } from "../../routing/project-route.js";
import type { InspectorSelection } from "./ContextInspector.js";
import { Button } from "../primitives/Button.js";
import { StatusBadge } from "../primitives/StatusBadge.js";

type Summary = DecisionSummaryDto | IssueSummaryDto | EvidenceSummaryDto | EpisodeSummaryDto | ObjectReceiptSummaryDto;
type Detail = DecisionDetailDto | IssueDetailDto | EvidenceDetailDto | EpisodeDetailDto | ObjectReceiptDetailDto;
type LedgerKind = Exclude<ResearchObjectKind, "appeal" | "deliberation_room">;

interface ResearchObjectWorkspaceProps {
  readonly language: AppLanguage;
  readonly projectId: string;
  readonly route: ProjectRoute;
  readonly onNavigate: (href: string) => void;
  readonly onInspect: (selection: InspectorSelection) => void;
  readonly onError: (error: unknown) => void;
  readonly onNotice: (message: string, tone?: "ready" | "warning" | "danger") => void;
  readonly onAuthorityChanged: () => Promise<void>;
}

function c(language: AppLanguage, en: string, zh: string): string { return language === "en" ? en : zh; }
function date(language: AppLanguage, value: string): string { try { return new Intl.DateTimeFormat(language, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); } catch { return value; } }
function statusOf(item: Summary | Detail): string { return "status" in item ? item.status : "state" in item ? item.state : "current"; }
function titleOf(item: Summary | Detail): string { return "statement" in item ? item.statement : "summary" in item ? item.summary : item.kind === "episode" ? `Episode ${item.id}` : `Receipt ${item.id}`; }
function pretty(value: unknown): string { return typeof value === "string" ? value : JSON.stringify(value, null, 2); }
function formText(value: FormDataEntryValue | null, fallback = ""): string { return typeof value === "string" ? value : fallback; }
function displayText(value: unknown, fallback = "unknown"): string {
  return typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : fallback;
}
function lines(value: FormDataEntryValue | null): string[] { return formText(value).split(/\r?\n/u).map((item) => item.trim()).filter(Boolean); }
function jsonArray(value: FormDataEntryValue | null, label: string, language: AppLanguage): readonly unknown[] {
  let parsed: unknown;
  try { parsed = JSON.parse(formText(value, "[]")); } catch { throw new Error(c(language, `${label} must be valid JSON.`, `${label} 必须是有效的 JSON。`)); }
  if (!Array.isArray(parsed)) throw new Error(c(language, `${label} must be a JSON array.`, `${label} 必须是 JSON 数组。`));
  return parsed;
}

export function ResearchObjectWorkspace(props: ResearchObjectWorkspaceProps) {
  if (props.route.workspace === "overview") return <OverviewWorkspace {...props} />;
  if (props.route.workspace === "brief") return <BriefWorkspace {...props} />;
  if (props.route.workspace === "attention") return <AttentionWorkspace {...props} />;
  if (["decision", "issue", "evidence", "episode", "receipt"].includes(props.route.workspace)) return <LedgerWorkspace {...props} kind={props.route.workspace as LedgerKind} />;
  return <section className="object-workspace" aria-labelledby="workspace-not-found"><header className="workspace-section-header"><div><p className="eyebrow">PROJECT</p><h1 id="workspace-not-found">{c(props.language, "Workspace not found", "未找到工作区")}</h1><p>{c(props.language, "This link does not identify a current project object.", "这个链接未指向当前项目中的有效对象。")}</p></div></header><Button type="button" onClick={() => { props.onNavigate("/project/overview"); }}>{c(props.language, "Open Overview", "打开项目概览")}</Button></section>;
}

function useProjection<T>(load: () => Promise<T>, dependencies: readonly unknown[], onError: (error: unknown) => void) {
  const [value, setValue] = useState<T>();
  const [loading, setLoading] = useState(true);
  const requestSequence = useRef(0);
  const refresh = useCallback(async () => {
    const request = ++requestSequence.current;
    setLoading(true);
    try {
      const next = await load();
      if (request === requestSequence.current) setValue(next);
    } catch (error) {
      if (request === requestSequence.current) onError(error);
    } finally {
      if (request === requestSequence.current) setLoading(false);
    }
  }, dependencies);
  useEffect(() => {
    setValue(undefined);
    void refresh();
    return () => { requestSequence.current += 1; };
  }, [refresh]);
  const commit = useCallback((next: T | undefined) => {
    requestSequence.current += 1;
    setValue(next);
    setLoading(false);
  }, []);
  return { value, loading, refresh, setValue: commit };
}

function OverviewWorkspace(props: ResearchObjectWorkspaceProps) {
  const projection = useProjection<ProjectOverviewDto>(() => researchRoomApi.projectOverview(), [props.projectId], props.onError);
  const value = projection.value;
  const currentEpisode = value?.currentEpisode;
  const latestReceipt = value?.latestReceipt;
  return <section className="object-workspace" aria-labelledby="overview-title">
    <header className="workspace-section-header"><div><p className="eyebrow">PROJECT OVERVIEW</p><h1 id="overview-title">{c(props.language, "Project Overview", "项目概览")}</h1><p>{c(props.language, "Recover the current question, smallest task, unresolved work, and latest structured change.", "恢复当前问题、最小任务、未决事项和最近的真实结构化变化。")}</p></div><Button type="button" variant="quiet" disabled={projection.loading} onClick={() => { void projection.refresh(); }}>{c(props.language, "Refresh", "刷新")}</Button></header>
    {projection.loading && !value ? <p role="status" className="empty-state">{c(props.language, "Reading local project state…", "正在读取本地项目状态……")}</p> : null}
    {value ? <>
      <section className="overview-primary" aria-labelledby="overview-question"><p className="nav-label">RESEARCH LINE</p><h2 id="overview-question">{value.brief.question}</h2><dl className="object-facts"><dt>{c(props.language, "Stage", "阶段")}</dt><dd>{value.brief.stage}</dd><dt>{c(props.language, "Smallest task", "当前最小任务")}</dt><dd>{value.brief.task}</dd><dt>Brief</dt><dd>v{value.brief.versionNumber}</dd><dt>Provider</dt><dd>{value.providerStatus}</dd></dl><button type="button" className="text-link" onClick={() => { props.onNavigate("/project/brief"); }}>{c(props.language, "Inspect the complete Research Brief", "查看完整 Research Brief")}</button></section>
      <section aria-labelledby="overview-continuity"><div className="section-heading"><h2 id="overview-continuity">{c(props.language, "Continuity anchors", "研究连续性锚点")}</h2><span>{c(props.language, "Canonical objects", "Canonical 对象")}</span></div><div className="continuity-anchors">{currentEpisode ? <button type="button" onClick={() => { props.onNavigate(currentEpisode.href); }}><span>{c(props.language, "Current Episode", "当前 Episode")}</span><strong>{currentEpisode.id}</strong><small>{currentEpisode.status} · {date(props.language, currentEpisode.updatedAt)}</small></button> : <div className="empty-state"><strong>{c(props.language, "Current Episode", "当前 Episode")}</strong><span>{c(props.language, "No Episode has been recorded.", "尚未记录 Episode。")}</span></div>}{latestReceipt ? <button type="button" onClick={() => { props.onNavigate(latestReceipt.href); }}><span>{c(props.language, "Latest actual Receipt", "最近一次真实 Receipt")}</span><strong>{latestReceipt.disposition}</strong><small>{latestReceipt.status} · {date(props.language, latestReceipt.updatedAt)}</small></button> : <div className="empty-state"><strong>{c(props.language, "Latest actual Receipt", "最近一次真实 Receipt")}</strong><span>{c(props.language, "No disposition has produced a Receipt.", "尚无 disposition 生成 Receipt。")}</span></div>}</div></section>
      <section aria-labelledby="overview-ledgers"><div className="section-heading"><h2 id="overview-ledgers">{c(props.language, "Structured ledgers", "结构化账本")}</h2><span>{c(props.language, "Navigable summaries", "可导航摘要")}</span></div><div className="overview-ledger-lines">
        {([ ["decision", value.counts.decisions], ["issue", value.counts.issues], ["evidence", value.counts.evidence], ["episode", value.counts.episodes], ["receipt", value.counts.receipts], ["appeal", value.counts.appeals] ] as const).map(([kind, count]) => <button key={kind} type="button" onClick={() => { props.onNavigate(`/project/${kind === "decision" ? "decisions" : kind === "issue" ? "issues" : kind === "evidence" ? "evidence" : kind === "episode" ? "episodes" : kind === "receipt" ? "receipts" : "appeals"}`); }}><span>{kind}</span><strong>{count}</strong><small>{Object.entries(value.statuses[kind === "decision" ? "decisions" : kind === "issue" ? "issues" : kind === "evidence" ? "evidence" : kind === "episode" ? "episodes" : kind === "receipt" ? "receipts" : "appeals"]).map(([status, statusCount]) => `${status} ${statusCount}`).join(" · ") || c(props.language, "Empty", "空")}</small></button>)}
      </div></section>
      <section aria-labelledby="overview-attention"><div className="section-heading"><h2 id="overview-attention">{c(props.language, "Needs your attention", "需要你的处理")}</h2><span>{value.attention.total}</span></div>{value.attention.top.length ? <ol className="structured-list">{value.attention.top.map((item) => <li key={`${item.kind}-${item.id}`}><button type="button" onClick={() => { props.onNavigate(item.href); }}><span><strong>{item.title}</strong><small>{item.reason}</small></span><StatusBadge tone="warning">{item.kind}</StatusBadge></button></li>)}</ol> : <p className="empty-state">{c(props.language, "No canonical object currently requires a user action.", "当前没有需要用户动作的 canonical 对象。")}</p>}<button type="button" className="text-link" onClick={() => { props.onNavigate("/project/attention"); }}>{c(props.language, "Open Attention", "打开 Attention")}</button></section>
      <section aria-labelledby="overview-recent"><div className="section-heading"><h2 id="overview-recent">{c(props.language, "Recent structured changes", "最近的结构化变化")}</h2><span>{c(props.language, "No activity feed", "不是活动流")}</span></div>{value.recentChanges.length ? <ol className="timeline-list">{value.recentChanges.map((item) => <li key={`${item.kind}-${item.id}-${item.at}`}><button type="button" onClick={() => { props.onNavigate(item.href); }}><time dateTime={item.at}>{date(props.language, item.at)}</time><span><strong>{item.label}</strong><small>{item.kind} · {item.status}</small></span></button></li>)}</ol> : <p className="empty-state">{c(props.language, "The active Brief is the only recorded project state.", "当前只有 Active Brief 这一项项目状态。")}</p>}</section>
    </> : null}
  </section>;
}

function BriefWorkspace(props: ResearchObjectWorkspaceProps) {
  const projection = useProjection<BriefWorkspaceDto>(() => researchRoomApi.briefWorkspace(), [props.projectId], props.onError);
  const [editing, setEditing] = useState(false); const [formError, setFormError] = useState<string>(); const [busy, setBusy] = useState(false);
  const value = projection.value;
  async function propose(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault(); if (!value) return; setFormError(undefined); setBusy(true);
    try {
      const data = new FormData(event.currentTarget);
      const next: Readonly<Record<string, unknown>> = {
        projectQuestion: formText(data.get("projectQuestion")).trim(), currentStage: formText(data.get("currentStage")), currentTask: formText(data.get("currentTask")).trim(),
        targetArtifacts: lines(data.get("targetArtifacts")), fixedDecisions: jsonArray(data.get("fixedDecisions"), c(props.language, "Fixed Decisions", "固定决定"), props.language), allowedChanges: jsonArray(data.get("allowedChanges"), c(props.language, "Allowed Changes", "允许的变更"), props.language), forbiddenChanges: jsonArray(data.get("forbiddenChanges"), c(props.language, "Forbidden Changes", "禁止的变更"), props.language), expectedDeltas: jsonArray(data.get("expectedDeltas"), c(props.language, "Expected Deltas", "预期增量"), props.language), evidenceBoundaries: jsonArray(data.get("evidenceBoundaries"), c(props.language, "Evidence Boundaries", "证据边界"), props.language), explicitNonGoals: lines(data.get("explicitNonGoals")),
      };
      if (!next.projectQuestion || !next.currentTask) throw new Error(c(props.language, "Question and current task are required.", "研究问题和当前任务不能为空。"));
      const changes = Object.fromEntries(Object.entries(next).filter(([key, item]) => JSON.stringify(item) !== JSON.stringify(value.active[key as keyof BriefVersionDto])));
      if (Object.keys(changes).length === 0) throw new Error(c(props.language, "No structured field changed.", "没有结构字段发生变化。"));
      const reason = formText(data.get("reason")).trim(); if (!reason) throw new Error(c(props.language, "Explain why this candidate is needed.", "请说明为什么需要这个 candidate。"));
      projection.setValue(await researchRoomApi.proposeBriefCandidate(props.projectId, value.entityVersion, changes, reason)); setEditing(false); props.onNotice(c(props.language, "Brief candidate saved. The active Brief did not change.", "Brief candidate 已保存，Active Brief 未改变。"), "ready");
    } catch (error) { setFormError(error instanceof Error ? error.message : String(error)); }
    finally { setBusy(false); }
  }
  async function activate(candidate: BriefCandidateDto, reason: string) {
    if (!value) return; setBusy(true); try { const result = await researchRoomApi.activateBriefCandidate(props.projectId, candidate.id, value.entityVersion, reason); projection.setValue(result.workspace); await props.onAuthorityChanged(); props.onNotice(c(props.language, "Brief candidate activated and the durable YAML projection was published.", "Brief candidate 已激活，并同步发布持久 YAML 投影。"), "ready"); } catch (error) { props.onError(error); } finally { setBusy(false); }
  }
  return <section className="object-workspace" aria-labelledby="brief-title"><header className="workspace-section-header"><div><p className="eyebrow">RESEARCH BRIEF</p><h1 id="brief-title">{c(props.language, "Research Brief", "Research Brief 工作区")}</h1><p>{c(props.language, "The active Brief is read-only. Editing creates a pending candidate for a separate Authority Gate.", "Active Brief 默认只读；编辑只会创建 pending candidate，激活需要单独 Authority Gate。")}</p></div><div className="header-actions"><Button type="button" variant="quiet" disabled={projection.loading || busy} onClick={() => { void projection.refresh(); }}>{c(props.language, "Reload current version", "重新加载当前版本")}</Button><Button type="button" disabled={!value || busy} onClick={() => { setEditing((current) => !current); }}>{editing ? c(props.language, "Close editor", "关闭编辑") : c(props.language, "Create candidate", "创建 candidate")}</Button></div></header>
    {!value ? <p role="status" className="empty-state">{c(props.language, "Reading the active Brief…", "正在读取 Active Brief……")}</p> : <>
      <StatusBadge tone="ready">active · v{value.active.versionNumber}</StatusBadge>
      <BriefFields language={props.language} brief={value.active} briefId={value.briefId} entityVersion={value.entityVersion} onInspect={() => { props.onInspect({ kind: "research_object", title: "Research Brief", status: "active", fields: [{ label: "Brief ID", value: value.briefId }, { label: "Version ID", value: value.active.id }, { label: "Record version", value: String(value.entityVersion) }, { label: "Authority", value: displayText(value.active.source.authority) }, { label: "Created / activated", value: value.active.createdAt }] }); }} />
      {editing ? <BriefCandidateForm language={props.language} active={value.active} busy={busy} error={formError} onSubmit={propose} /> : null}
      <section aria-labelledby="brief-candidates"><div className="section-heading"><h2 id="brief-candidates">{c(props.language, "Candidates and field diff", "Candidates 与字段 Diff")}</h2><span>{value.candidateCount}</span></div>{value.candidates.length ? <ol className="candidate-list">{value.candidates.map((candidate) => <li key={candidate.id}><BriefCandidate language={props.language} candidate={candidate} busy={busy} onActivate={activate} /></li>)}</ol> : <p className="empty-state">{c(props.language, "No pending or historical candidates.", "没有 pending 或历史 candidate。")}</p>}</section>
      <section aria-labelledby="brief-history"><div className="section-heading"><h2 id="brief-history">{c(props.language, "Version history", "版本历史")}</h2><span>{value.versionCount}{value.versionsTruncated ? "+" : ""}</span></div><ol className="timeline-list">{value.versions.map((version) => <li key={version.id}><div><time dateTime={version.createdAt}>{date(props.language, version.createdAt)}</time><span><strong>v{version.versionNumber} · {version.currentStage}</strong><small>{version.currentTask}</small></span></div></li>)}</ol></section>
    </>}
  </section>;
}

function BriefFields({ language, brief, briefId, entityVersion, onInspect }: { readonly language: AppLanguage; readonly brief: BriefVersionDto; readonly briefId: string; readonly entityVersion: number; readonly onInspect: () => void }) {
  const arrays = [ ["Target Artifacts", "目标产物", brief.targetArtifacts], ["Fixed Decisions", "固定决定", brief.fixedDecisions], ["Allowed Changes", "允许的变更", brief.allowedChanges], ["Forbidden Changes", "禁止的变更", brief.forbiddenChanges], ["Expected Deltas", "预期增量", brief.expectedDeltas], ["Evidence Boundaries", "证据边界", brief.evidenceBoundaries], ["Explicit Non-goals", "明确的非目标", brief.explicitNonGoals] ] as const;
  const actorKind = typeof brief.source.actor === "object" && brief.source.actor !== null && "kind" in brief.source.actor ? displayText(brief.source.actor.kind) : "unknown";
  return <section className="brief-structure" aria-labelledby="active-brief-fields"><div className="section-heading"><h2 id="active-brief-fields">{c(language, "Active structured fields", "当前结构化字段")}</h2><Button type="button" variant="quiet" data-inspector-return onClick={onInspect}>{c(language, "Inspect provenance", "检查来源")}</Button></div><dl className="brief-main-fields"><dt>{c(language, "Project Question", "研究问题")}</dt><dd>{brief.projectQuestion}</dd><dt>{c(language, "Current Stage", "当前阶段")}</dt><dd>{brief.currentStage}</dd><dt>{c(language, "Current Task", "当前任务")}</dt><dd>{brief.currentTask}</dd><dt>{c(language, "Brief / version ID", "Brief / 版本 ID")}</dt><dd>{briefId} / {brief.id}</dd><dt>{c(language, "Record version", "记录版本")}</dt><dd>{entityVersion}</dd><dt>{c(language, "Source / authority", "来源 / 权威")}</dt><dd>{displayText(brief.source.authority)} / {actorKind}</dd><dt>{c(language, "Created / activated", "创建 / 激活")}</dt><dd>{date(language, brief.createdAt)}</dd></dl>{arrays.map(([en, zh, items]) => <details key={en} open={en === "Expected Deltas" || en === "Evidence Boundaries"}><summary>{c(language, en, zh)} <span>{items.length}</span></summary>{items.length ? <pre className="structured-value">{pretty(items)}</pre> : <p className="empty-state">{c(language, "None recorded.", "尚未记录。")}</p>}</details>)}</section>;
}

function BriefCandidateForm({ language, active, busy, error, onSubmit }: { readonly language: AppLanguage; readonly active: BriefVersionDto; readonly busy: boolean; readonly error?: string; readonly onSubmit: (event: SyntheticEvent<HTMLFormElement>) => Promise<void> }) {
  const arrays = [ ["fixedDecisions", "Fixed Decisions", "固定决定", active.fixedDecisions], ["allowedChanges", "Allowed Changes", "允许的变更", active.allowedChanges], ["forbiddenChanges", "Forbidden Changes", "禁止的变更", active.forbiddenChanges], ["expectedDeltas", "Expected Deltas", "预期增量", active.expectedDeltas], ["evidenceBoundaries", "Evidence Boundaries", "证据边界", active.evidenceBoundaries] ] as const;
  return <form className="structured-editor" onSubmit={(event) => { void onSubmit(event); }}><h2>{c(language, "Candidate editor", "Candidate 编辑器")}</h2><p>{c(language, "Saving creates a proposal only. It never overwrites the active Brief.", "保存只会创建 proposal，绝不会覆盖 Active Brief。")}</p><label>{c(language, "Project Question", "研究问题")}<textarea name="projectQuestion" required defaultValue={active.projectQuestion} /></label><label>{c(language, "Current Stage", "当前阶段")}<select name="currentStage" defaultValue={active.currentStage}><option value="question_formulation">question_formulation</option><option value="literature_review">literature_review</option><option value="design">design</option><option value="analysis">analysis</option><option value="revision">revision</option><option value="submission">submission</option></select></label><label>{c(language, "Current Task", "当前任务")}<textarea name="currentTask" required defaultValue={active.currentTask} /></label><label>{c(language, "Target Artifacts", "目标产物")} <small>{c(language, "one canonical ID per line", "每行一个 canonical ID")}</small><textarea name="targetArtifacts" defaultValue={active.targetArtifacts.join("\n")} /></label>{arrays.map(([name, en, zh, items]) => <label key={name}>{c(language, en, zh)} <small>{c(language, "JSON array", "JSON 数组")}</small><textarea className="code-input" name={name} defaultValue={JSON.stringify(items, null, 2)} /></label>)}<label>{c(language, "Explicit Non-goals", "明确的非目标")} <small>{c(language, "one per line", "每行一项")}</small><textarea name="explicitNonGoals" defaultValue={active.explicitNonGoals.join("\n")} /></label><label>{c(language, "Candidate reason", "Candidate 理由")}<textarea name="reason" required /></label>{error ? <p className="inline-error" role="alert">{error}</p> : null}<Button type="submit" disabled={busy}>{c(language, "Save pending candidate", "保存 pending candidate")}</Button></form>;
}

function BriefCandidate({ language, candidate, busy, onActivate }: { readonly language: AppLanguage; readonly candidate: BriefCandidateDto; readonly busy: boolean; readonly onActivate: (candidate: BriefCandidateDto, reason: string) => Promise<void> }) {
  const [reason, setReason] = useState(""); const [acknowledged, setAcknowledged] = useState(false);
  return <article className="candidate"><header><div><StatusBadge tone={candidate.status === "pending" ? "warning" : "neutral"}>{candidate.status}</StatusBadge><h3>{candidate.reason}</h3><small>{date(language, candidate.createdAt)}</small></div></header><div className="impact-ledger"><strong>{c(language, "Impact before activation", "激活前影响")}</strong><span>{candidate.impact.highImpactDirectionChange ? c(language, "High impact: research question changes", "高影响：研究问题将改变") : c(language, "Research question preserved", "研究问题保持不变")}</span><span>{c(language, "Current task", "当前任务")}: {candidate.impact.currentTaskChanged ? c(language, "changes", "改变") : c(language, "unchanged", "不变")}</span><span>{c(language, "Fixed Decisions", "固定决定")}: {candidate.impact.fixedDecisionsChanged ? c(language, "changes", "改变") : c(language, "unchanged", "不变")}</span><span>{c(language, "Evidence boundary", "证据边界")}: {candidate.impact.evidenceBoundaryEffect}</span><span>{c(language, "Removed non-goals", "删除的非目标")}: {candidate.impact.explicitNonGoalsRemoved.join(" · ") || c(language, "none", "无")}</span><span>{c(language, "Review", "审查")}: {candidate.impact.reviewImpact}</span><span>{c(language, "Manifest", "清单")}: {candidate.impact.manifestImpact}</span><span>{c(language, "Expected record version", "预期记录版本")}: {candidate.impact.expectedEntityVersion}</span>{candidate.impact.activeEpisodeIds.length ? <span>{c(language, "Affected Episodes", "受影响 Episodes")}: {candidate.impact.activeEpisodeIds.join(" · ")}{candidate.impact.activeEpisodesTruncated ? " …" : ""}</span> : null}</div><div className="field-diff" role="table" aria-label={c(language, "Structured field diff", "结构化字段 diff")}>{candidate.diff.map((field) => <div role="row" key={field.field} data-change={field.change}><strong role="cell">{field.field}</strong><StatusBadge tone={field.change === "unchanged" ? "neutral" : "warning"}>{field.change}</StatusBadge>{field.change !== "unchanged" ? <details><summary>{c(language, "Before / after", "变更前 / 后")}</summary><div className="diff-values"><pre>{pretty(field.before)}</pre><pre>{pretty(field.after)}</pre></div></details> : null}</div>)}</div>{candidate.status === "pending" ? <div className="authority-gate"><h4>{c(language, "Authority Gate", "权威门禁")}</h4><label>{c(language, "Activation reason", "激活理由")}<textarea value={reason} onChange={(event) => { setReason(event.target.value); }} /></label><label className="check-line"><input type="checkbox" checked={acknowledged} onChange={(event) => { setAcknowledged(event.target.checked); }} />{c(language, "I reviewed the field diff and impact. Saving the candidate did not activate it.", "我已核对字段 diff 与影响，并确认保存 candidate 并未激活它。")}</label><Button type="button" disabled={busy || !acknowledged || !reason.trim()} onClick={() => { void onActivate(candidate, reason.trim()); }}>{c(language, "Activate candidate", "激活 candidate")}</Button></div> : null}</article>;
}

function AttentionWorkspace(props: ResearchObjectWorkspaceProps) {
  const projection = useProjection<AttentionDto>(() => researchRoomApi.attention(), [props.projectId], props.onError);
  return <section className="object-workspace" aria-labelledby="attention-title"><header className="workspace-section-header"><div><p className="eyebrow">ATTENTION</p><h1 id="attention-title">{c(props.language, "Attention", "Attention 待处理")}</h1><p>{c(props.language, "A rebuildable view of canonical objects that still require a user action. Hiding a reminder would not resolve its object.", "这是仍需用户动作的 canonical 对象可重建投影；隐藏提醒不等于解决 underlying 对象。")}</p></div><Button type="button" variant="quiet" onClick={() => { void projection.refresh(); }}>{c(props.language, "Refresh", "刷新")}</Button></header>{projection.value?.items.length ? <ol className="structured-list attention-list">{projection.value.items.map((item) => <li key={`${item.kind}-${item.id}`}><button type="button" onClick={() => { props.onNavigate(item.href); }}><span><strong>{item.title}</strong><small>{item.reason}<br/>{item.primaryAction} · {date(props.language, item.createdAt)}</small></span><StatusBadge tone={item.severity === "high" ? "warning" : "neutral"}>{item.kind}</StatusBadge></button></li>)}</ol> : <p className="empty-state">{projection.loading ? c(props.language, "Deriving Attention…", "正在派生 Attention……") : c(props.language, "Nothing currently requires a user action.", "当前没有需要用户动作的事项。")}</p>}</section>;
}

function LedgerWorkspace(props: ResearchObjectWorkspaceProps & { readonly kind: LedgerKind }) {
  const [status, setStatus] = useState("");
  const [query, setQuery] = useState("");
  const [source, setSource] = useState("");
  const [scope, setScope] = useState("");
  const [active, setActive] = useState("");
  const [referenced, setReferenced] = useState("");
  const [issueKind, setIssueKind] = useState("");
  const [relevance, setRelevance] = useState("");
  const [unresolved, setUnresolved] = useState("");
  const [disposition, setDisposition] = useState("");
  const [providerStatus, setProviderStatus] = useState("");
  const [cursor, setCursor] = useState<string>();
  const [history, setHistory] = useState<(string | undefined)[]>([]);
  function resetPage() { setHistory([]); setCursor(undefined); }
  const request: WorkspaceListRequest = {
    limit: 50,
    ...(cursor ? { cursor } : {}),
    ...(status ? { status } : {}),
    ...(query ? { query } : {}),
    ...(source && props.kind !== "receipt" ? { source } : {}),
    ...(props.kind === "decision" && scope ? { scope } : {}),
    ...(props.kind === "decision" && active ? { active: active === "true" } : {}),
    ...(props.kind === "decision" && referenced ? { referencedByCurrentBrief: referenced === "true" } : {}),
    ...(props.kind === "issue" && issueKind ? { issueKind } : {}),
    ...(props.kind === "issue" && relevance ? { relevance: "current_brief" as const } : {}),
    ...(props.kind === "issue" && unresolved ? { unresolved: unresolved === "true" } : {}),
    ...(props.kind === "receipt" && disposition ? { disposition } : {}),
    ...(props.kind === "receipt" && providerStatus ? { providerStatus } : {}),
  };
  const objectId = props.route.objectId;
  const load = objectId
    ? async () => await researchRoomApi.researchObject(props.kind, objectId) as Detail
    : async () => await researchRoomApi.listResearchObjects(props.kind, request) as WorkspacePage<Summary>;
  const projection = useProjection<Detail | WorkspacePage<Summary>>(
    load,
    [props.projectId, props.kind, props.route.objectId, cursor, status, query, source, scope, active, referenced, issueKind, relevance, unresolved, disposition, providerStatus],
    props.onError,
  );
  const value = projection.value;
  if (objectId) return <ObjectDetailWorkspace {...props} detail={value && "kind" in value ? value : undefined} loading={projection.loading} onRefresh={projection.refresh} />;
  const page = value && "items" in value ? value : undefined;
  const options = props.kind === "decision" ? ["proposed", "accepted", "frozen", "rejected", "deferred", "superseded"] : props.kind === "issue" ? ["open", "acknowledged", "reopened", "disputed", "resolved", "waived", "suppressed"] : props.kind === "evidence" ? ["current", "stale", "disputed"] : props.kind === "episode" ? ["draft", "active", "candidate_submitted", "reviewed", "user_action_required", "accepted", "rejected", "abandoned"] : ["committed", "rolled_back"];
  const sources = ["user", "model", "system", "import"];
  const issueKinds = ["target_substitution", "repeated_audit", "argument_leap", "pseudo_depth", "evidence_boundary", "scope_violation", "decision_violation", "factual_error", "methodological"];
  return <section className="object-workspace" aria-labelledby="ledger-title">
    <header className="workspace-section-header"><div><p className="eyebrow">{props.kind.toUpperCase()} LEDGER</p><h1 id="ledger-title">{ledgerTitle(props.language, props.kind)}</h1><p>{ledgerDeck(props.language, props.kind)}</p></div>{props.kind === "decision" ? <DecisionCreate projectId={props.projectId} language={props.language} onError={props.onError} onCreated={(detail) => { props.onNavigate(`/project/decisions/${detail.id}`); }} /> : null}</header>
    <form className="ledger-filters" aria-label={c(props.language, `${props.kind} filters`, `${props.kind} 筛选`)} onSubmit={(event) => { event.preventDefault(); resetPage(); }}>
      <label>{c(props.language, "Status", "状态")}<select value={status} onChange={(event) => { setStatus(event.target.value); resetPage(); }}><option value="">{c(props.language, "All statuses", "全部状态")}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>
      {props.kind !== "receipt" ? <label>{c(props.language, "Source", "来源")}<select value={source} onChange={(event) => { setSource(event.target.value); resetPage(); }}><option value="">{c(props.language, "All sources", "全部来源")}</option>{sources.map((option) => <option key={option} value={option}>{option}</option>)}</select></label> : null}
      {props.kind === "decision" ? <><label>{c(props.language, "Scope", "范围")}<select value={scope} onChange={(event) => { setScope(event.target.value); resetPage(); }}><option value="">{c(props.language, "All scopes", "全部范围")}</option>{["project", "artifact", "brief", "issue"].map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>{c(props.language, "Activity", "当前性")}<select value={active} onChange={(event) => { setActive(event.target.value); resetPage(); }}><option value="">{c(props.language, "Active and historical", "当前与历史")}</option><option value="true">{c(props.language, "Active only", "仅当前")}</option><option value="false">{c(props.language, "Historical only", "仅历史")}</option></select></label><label>{c(props.language, "Current Brief reference", "当前 Brief 引用")}<select value={referenced} onChange={(event) => { setReferenced(event.target.value); resetPage(); }}><option value="">{c(props.language, "Any reference", "全部")}</option><option value="true">{c(props.language, "Referenced", "已引用")}</option><option value="false">{c(props.language, "Not referenced", "未引用")}</option></select></label></> : null}
      {props.kind === "issue" ? <><label>{c(props.language, "Kind", "类型")}<select value={issueKind} onChange={(event) => { setIssueKind(event.target.value); resetPage(); }}><option value="">{c(props.language, "All kinds", "全部类型")}</option>{issueKinds.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>{c(props.language, "Brief relevance", "Brief 相关性")}<select value={relevance} onChange={(event) => { setRelevance(event.target.value); resetPage(); }}><option value="">{c(props.language, "Any relevance", "全部")}</option><option value="current_brief">{c(props.language, "Current Brief", "当前 Brief")}</option></select></label><label>{c(props.language, "Resolution", "解决状态")}<select value={unresolved} onChange={(event) => { setUnresolved(event.target.value); resetPage(); }}><option value="">{c(props.language, "Resolved and unresolved", "已解决与未解决")}</option><option value="true">{c(props.language, "Unresolved only", "仅未解决")}</option><option value="false">{c(props.language, "Resolved only", "仅已解决")}</option></select></label></> : null}
      {props.kind === "receipt" ? <><label>{c(props.language, "Disposition", "处置")}<select value={disposition} onChange={(event) => { setDisposition(event.target.value); resetPage(); }}><option value="">{c(props.language, "All dispositions", "全部处置")}</option>{["accept", "reject", "modify_accept", "defer", "direction_change"].map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>{c(props.language, "Provider result", "Provider 结果")}<select value={providerStatus} onChange={(event) => { setProviderStatus(event.target.value); resetPage(); }}><option value="">{c(props.language, "All Provider states", "全部 Provider 状态")}</option><option value="semantic_ready">semantic_ready</option><option value="ledger_only">ledger_only</option></select></label></> : null}
      <label className="filter-search">{c(props.language, "Structured search", "结构化字段搜索")}<input value={query} onChange={(event) => { setQuery(event.target.value); resetPage(); }} placeholder={c(props.language, "Search this ledger", "搜索当前账本")} /></label>
    </form>
    {projection.loading && !page ? <p role="status" className="empty-state">{c(props.language, "Reading the local ledger…", "正在读取本地账本……")}</p> : null}
    {page ? <>{page.items.length ? <ol className="structured-list ledger-list">{page.items.map((item) => <li key={item.id}><button type="button" onClick={() => { props.onNavigate(`/project/${props.kind === "decision" ? "decisions" : props.kind === "issue" ? "issues" : props.kind === "evidence" ? "evidence" : props.kind === "episode" ? "episodes" : "receipts"}/${item.id}`); }}><span><strong>{titleOf(item)}</strong><small>{summaryLine(item)} · {"updatedAt" in item ? date(props.language, item.updatedAt) : ""}</small></span><StatusBadge tone="neutral">{statusOf(item)}</StatusBadge></button></li>)}</ol> : <p className="empty-state">{emptyLedger(props.language, props.kind)}</p>}<nav className="pagination" aria-label={c(props.language, "Ledger pages", "账本分页")}><Button type="button" variant="quiet" disabled={history.length === 0} onClick={() => { const previous = [...history]; const prior = previous.pop(); setHistory(previous); setCursor(prior); }}>{c(props.language, "Previous", "上一页")}</Button><span>{c(props.language, "Up to 50 objects on this page", "本页最多 50 个对象")}</span><Button type="button" variant="quiet" disabled={!page.nextCursor} onClick={() => { setHistory((current) => [...current, cursor]); setCursor(page.nextCursor); }}>{c(props.language, "Next", "下一页")}</Button></nav></> : null}
  </section>;
}

function ObjectDetailWorkspace(props: ResearchObjectWorkspaceProps & { readonly kind: ResearchObjectKind; readonly detail?: Detail; readonly loading: boolean; readonly onRefresh: () => Promise<void> }) {
  const detail = props.detail;
  if (!detail) return <section className="object-workspace"><p role="status" className="empty-state">{props.loading ? c(props.language, "Reading object detail…", "正在读取对象详情……") : c(props.language, "The object is unavailable in this project.", "当前项目中没有这个对象。")}</p></section>;
  const relations = relationLinks(detail);
  const inspect = () => { props.onInspect({ kind: "research_object", title: titleOf(detail), status: statusOf(detail), fields: [{ label: "ID", value: detail.id }, { label: "Version", value: String(detail.version) }, ...("provenance" in detail ? [{ label: "Authority", value: detail.provenance.authority }, { label: "Source", value: detail.provenance.actorKind }, { label: "Recorded", value: detail.provenance.recordedAt }] : []), ...(detail.kind === "receipt" ? [{ label: "Hash", value: detail.receiptHash }, { label: "Provider", value: detail.providerStatus }] : [])], relations }); };
  return <section className="object-workspace" aria-labelledby="object-title"><header className="workspace-section-header"><div><p className="eyebrow">{props.kind.toUpperCase()} DETAIL</p><h1 id="object-title">{titleOf(detail)}</h1><p>{detail.kind === "decision" ? detail.rationale : detail.kind === "issue" ? detail.violatedCriterion : detail.kind === "evidence" ? `${detail.evidenceKind} · ${detail.inferenceCapacity}` : detail.kind === "episode" ? `${detail.status} · ${detail.artifactId}` : displayText(detail.disposition.kind, "disposition")}</p></div><div className="header-actions"><Button type="button" variant="quiet" onClick={() => { props.onNavigate(`/project/${props.kind === "decision" ? "decisions" : props.kind === "issue" ? "issues" : props.kind === "evidence" ? "evidence" : props.kind === "episode" ? "episodes" : "receipts"}`); }}>{c(props.language, "Back to list", "返回列表")}</Button><Button type="button" variant="quiet" data-inspector-return onClick={inspect}>{c(props.language, "Inspect", "检查")}</Button></div></header><StatusBadge tone="neutral">{statusOf(detail)}</StatusBadge><ObjectDetailBody language={props.language} detail={detail} onNavigate={props.onNavigate} />{detail.kind === "issue" ? <IssueDeliberationEntry language={props.language} detail={detail} onNavigate={props.onNavigate} /> : null}{relations.length ? <section className="structured-section" aria-labelledby="related-objects"><h2 id="related-objects">{c(props.language, "Related canonical objects", "相关 canonical 对象")}</h2><div className="relation-actions">{relations.map((relation) => <button className="text-link" type="button" key={`${relation.label}-${relation.href}`} onClick={() => { props.onNavigate(relation.href); }}>{relation.label}</button>)}</div>{"relationsTruncated" in detail && detail.relationsTruncated ? <p className="inline-warning">{c(props.language, "Only the bounded one-hop relation set is shown.", "这里只显示受限的一跳关系集。")}</p> : null}</section> : null}{detail.kind === "decision" ? <DecisionActions language={props.language} projectId={props.projectId} detail={detail} onChanged={async (next) => { await props.onAuthorityChanged(); if (next.id === detail.id) await props.onRefresh(); else props.onNavigate(`/project/decisions/${next.id}`); }} onError={props.onError} /> : null}{detail.kind === "issue" ? <IssueActions language={props.language} projectId={props.projectId} detail={detail} onChanged={async () => { await props.onAuthorityChanged(); await props.onRefresh(); }} onError={props.onError} /> : null}{detail.kind === "receipt" ? <ReceiptActions language={props.language} projectId={props.projectId} detail={detail} onChanged={async () => { await props.onAuthorityChanged(); await props.onRefresh(); }} onError={props.onError} /> : null}</section>;
}

function IssueDeliberationEntry({ language, detail, onNavigate }: { readonly language: AppLanguage; readonly detail: IssueDetailDto; readonly onNavigate: (href: string) => void }) {
  if (!["open", "acknowledged", "reopened", "disputed"].includes(detail.status)) return null;
  const params = new URLSearchParams({ sourceKind: "research_issue", source: detail.id, revision: detail.sourceRevisionId, question: detail.summary, title: c(language, `Deliberate: ${detail.summary}`, `会商：${detail.summary}`) });
  return <section className="deliberation-entry" aria-labelledby="issue-deliberation-entry-title"><div><p className="eyebrow">TWO ISOLATED VIEWS</p><h2 id="issue-deliberation-entry-title">{c(language, "This open issue can enter a bounded deliberation", "这个开放 Issue 可以进入有限会商")}</h2><p>{c(language, "Use this only when two reasonable interpretations remain. The Issue stays unchanged until a separate Issue Authority command.", "仅在仍有两种合理解释时使用；除非另行执行 Issue Authority 命令，否则该 Issue 不会被改变。")}</p></div><Button type="button" variant="secondary" onClick={() => { onNavigate(`/project/deliberation-rooms/new?${params.toString()}`); }}>{c(language, "Start Deliberation Room", "发起会商室")}</Button></section>;
}

function ObjectDetailBody({ language, detail, onNavigate }: { readonly language: AppLanguage; readonly detail: Detail; readonly onNavigate: (href: string) => void }) {
  if (detail.kind === "decision") return <><dl className="object-facts"><dt>{c(language, "Scope", "范围")}</dt><dd>{pretty(detail.scope)}</dd><dt>Brief</dt><dd>{detail.effectiveBriefVersionId}</dd><dt>{c(language, "Current authority", "当前权威")}</dt><dd>{detail.provenance.authority} · {detail.provenance.actorKind}</dd><dt>{c(language, "Activity", "当前性")}</dt><dd>{detail.active ? c(language, "active", "当前") : c(language, "historical", "历史")} · {detail.referencedByCurrentBrief ? c(language, "referenced by current Brief", "被当前 Brief 引用") : c(language, "not referenced by current Brief", "未被当前 Brief 引用")}</dd><dt>{c(language, "Reopen conditions", "重开条件")}</dt><dd>{detail.reopenConditions.join(" · ") || "—"}</dd><dt>{c(language, "Created / updated", "创建 / 更新")}</dt><dd>{date(language, detail.createdAt)} · {date(language, detail.updatedAt)}</dd></dl><Lineage language={language} detail={detail} onNavigate={onNavigate} /><Timeline language={language} values={detail.timeline} /></>;
  if (detail.kind === "issue") return <><dl className="object-facts"><dt>{c(language, "Kind", "类型")}</dt><dd>{detail.issueKind}</dd><dt>{c(language, "Why it appeared", "出现原因")}</dt><dd>{detail.violatedCriterion} · {detail.rationaleConcepts.join(" · ")}</dd><dt>{c(language, "Target", "影响对象")}</dt><dd>{pretty(detail.target)}</dd><dt>Fingerprint</dt><dd><code>{detail.fingerprint}</code></dd><dt>{c(language, "First / last seen", "首次 / 最近出现")}</dt><dd>{date(language, detail.firstSeenAt)} · {date(language, detail.lastSeenAt)}</dd><dt>{c(language, "Recurrence", "复发")}</dt><dd>{detail.recurrenceCount}</dd><dt>{c(language, "Current user action", "当前用户动作")}</dt><dd>{detail.requiresUserAction ? c(language, "Required", "需要") : c(language, "Not required", "不需要")}</dd><dt>{c(language, "Resolution", "处置")}</dt><dd>{detail.resolution ? pretty(detail.resolution) : "—"}</dd><dt>{c(language, "Source", "来源")}</dt><dd>{detail.provenance.authority} · {detail.provenance.actorKind}</dd></dl><Timeline language={language} values={detail.timeline} />{detail.reopenHistory.length ? <StructuredSection language={language} title="Reopen history" value={detail.reopenHistory} /> : null}</>;
  if (detail.kind === "evidence") return <><dl className="object-facts"><dt>{c(language, "Source type", "来源类型")}</dt><dd>{detail.evidenceKind}</dd><dt>{c(language, "Safe locator", "安全定位")}</dt><dd>{pretty(detail.safeLocator)}</dd><dt>{c(language, "Artifact / revision", "Artifact / revision")}</dt><dd>{[detail.artifactId, detail.revisionId].filter(Boolean).join(" / ") || c(language, "No artifact locator", "无 artifact 定位")}</dd><dt>{c(language, "Content hash", "内容 hash")}</dt><dd><code>{detail.contentVersionHash ?? "not_recorded"}</code></dd><dt>{c(language, "Captured", "采集时间")}</dt><dd>{date(language, detail.capturedAt)}</dd><dt>{c(language, "Sensitivity / confidence", "敏感度 / 置信度")}</dt><dd>{detail.sensitivity} · {detail.confidence}</dd><dt>{c(language, "User verification", "用户核验")}</dt><dd>{detail.userVerificationState}</dd><dt>{c(language, "Inference / uncertainty", "推断能力 / 不确定性")}</dt><dd>{detail.inferenceCapacity} · {detail.uncertainty}</dd><dt>{c(language, "Source authority", "来源权威")}</dt><dd>{detail.provenance.authority} · {detail.provenance.actorKind}</dd></dl><StructuredSection language={language} title="Supporting / counter / limiting claim relations" value={detail.claimLinks} /><StructuredSection language={language} title="Mechanism relations" value={detail.mechanismLinks} />{detail.relationsTruncated ? <p className="inline-warning">{c(language, "Only the bounded one-hop relation set is shown.", "这里只显示受限的一跳关系集。")}</p> : null}</>;
  if (detail.kind === "episode") return <><dl className="object-facts"><dt>{c(language, "Current stage / task", "当前阶段 / 任务")}</dt><dd>{detail.lockedBrief ? `${detail.lockedBrief.stage} · ${detail.lockedBrief.task}` : c(language, "Not recorded in this Episode", "此 Episode 未记录")}</dd><dt>Artifact</dt><dd>{detail.artifactId}</dd><dt>Baseline</dt><dd>{displayText(detail.lockedStart.baselineRevisionId, "—")}</dd><dt>Candidate</dt><dd>{detail.candidateRevisionId ?? "—"}</dd><dt>{c(language, "Locked Brief", "锁定 Brief")}</dt><dd>{detail.lockedBrief?.versionId ?? displayText(detail.lockedStart.briefVersionId, "—")}</dd><dt>{c(language, "User action", "用户动作")}</dt><dd>{detail.status === "user_action_required" ? c(language, "Required", "需要") : c(language, "Not currently required", "当前不需要")}</dd><dt>{c(language, "Source", "来源")}</dt><dd>{detail.provenance.authority} · {detail.provenance.actorKind}</dd></dl><StructuredSection language={language} title="Locked decisions / issues / evidence boundary" value={detail.lockedStart} /><StructuredSection language={language} title="Findings and review runs" value={{ findingIds: detail.findingIds, reviewRunIds: detail.reviewRunIds }} /><StructuredSection language={language} title="ArgumentDelta from related Receipts" value={detail.argumentDeltas} />{detail.outcome ? <StructuredSection language={language} title="Outcome" value={detail.outcome} /> : null}<Timeline language={language} values={detail.timeline} /></>;
  return <><section className="trace"><h2>{c(language, "User-readable causal trace", "用户可读因果 Trace")}</h2><ol>{detail.trace.map((item) => <li key={item.step}><strong>{item.step.replaceAll("_", " ")}</strong><small>{item.summary}</small></li>)}</ol></section><ReceiptAppealEntry language={language} detail={detail} onNavigate={onNavigate} /><StructuredSection language={language} title="Findings" value={detail.findings} /><StructuredSection language={language} title="ArgumentDelta" value={detail.argumentDelta} /><StructuredSection language={language} title="Context Manifest fields" value={detail.contextFields} /><details><summary>{c(language, "Advanced IDs and hashes", "高级 ID 与 hash")}</summary><pre className="structured-value">{pretty({ id: detail.id, reviewId: detail.reviewId, receiptHash: detail.receiptHash, version: detail.version, beforeStateHash: detail.beforeStateHash, afterStateHash: detail.afterStateHash })}</pre></details></>;
}

function ReceiptAppealEntry({ language, detail, onNavigate }: { readonly language: AppLanguage; readonly detail: ObjectReceiptDetailDto; readonly onNavigate: (href: string) => void }) {
  return <section className="receipt-appeals" aria-labelledby="receipt-appeals-title"><div className="section-heading"><div><h2 id="receipt-appeals-title">{c(language, "Correction appeal", "纠错申诉")}</h2><p>{c(language, "Challenge only an eligible committed Semantic Judge finding. The Receipt remains immutable.", "只能针对符合条件且已提交的 Semantic Judge finding 申诉；Receipt 保持不可变。")}</p></div><StatusBadge tone={detail.appealableFindings.some((finding) => finding.action !== "unavailable") ? "warning" : "neutral"}>{detail.correctionAppeals.length}</StatusBadge></div>{detail.appealableFindings.length ? <ol className="receipt-finding-actions">{detail.appealableFindings.map((finding) => <li key={finding.findingId}><div><strong>{finding.kind}</strong><small>{finding.findingId} · {finding.severity}</small></div>{finding.action === "create_appeal" && finding.href ? <Button type="button" variant="secondary" onClick={() => { onNavigate(finding.href ?? "/project/appeals"); }}>{c(language, "Create appeal", "发起 Appeal")}</Button> : finding.action === "open_appeal" && finding.href ? <Button type="button" variant="quiet" onClick={() => { onNavigate(finding.href ?? "/project/appeals"); }}>{c(language, "Open appeal", "打开 Appeal")}</Button> : <span className="muted">{finding.unavailableReason ?? c(language, "Unavailable", "不可用")}</span>}</li>)}</ol> : <p className="empty-state">{c(language, "No committed semantic finding in this Receipt is appealable.", "此 Receipt 中没有可申诉的已提交语义 finding。")}</p>}</section>;
}

function StructuredSection({ language, title, value }: { readonly language: AppLanguage; readonly title: string; readonly value: unknown }) { return <section className="structured-section"><h2>{title}</h2>{Array.isArray(value) && value.length === 0 ? <p className="empty-state">{c(language, "None recorded.", "尚未记录。")}</p> : <pre className="structured-value">{pretty(value)}</pre>}</section>; }
function Timeline({ language, values }: { readonly language: AppLanguage; readonly values: readonly unknown[] }) {
  return <section className="structured-section"><h2>{c(language, "History", "历史")}</h2>{values.length ? <ol className="timeline-list">{values.map((raw, index) => {
    const item = typeof raw === "object" && raw !== null && !Array.isArray(raw) ? raw as Record<string, unknown> : {};
    const at = displayText(item.at, String(index + 1));
    return <li key={`${at}-${index}`}><div><time>{typeof item.at === "string" ? date(language, item.at) : String(index + 1)}</time><span><strong>{displayText(item.from, "created")} → {displayText(item.to, "state")}</strong><small>{displayText(item.reason, "")}</small></span></div></li>;
  })}</ol> : <p className="empty-state">{c(language, "No history recorded.", "尚无历史。")}</p>}</section>;
}
function Lineage({ language, detail, onNavigate }: { readonly language: AppLanguage; readonly detail: DecisionDetailDto; readonly onNavigate: (href: string) => void }) { return <section className="structured-section"><h2>{c(language, "Decision lineage", "Decision lineage")}</h2>{detail.lineage.length > 1 ? <ol className="lineage-list">{detail.lineage.map((item) => <li key={item.id} data-relation={item.relation}><button type="button" onClick={() => { onNavigate(`/project/decisions/${item.id}`); }}><span><strong>{item.statement}</strong><small>{item.relation} · {item.status} · v{item.version}</small></span></button></li>)}</ol> : <p className="empty-state">{c(language, "No replacement relation.", "没有替代关系。")}</p>}{detail.lineageTruncated ? <p className="inline-warning">{c(language, "The lineage is bounded; older ancestors remain in the canonical ledger.", "Lineage 为有界显示；更早祖先仍保留在 canonical 账本中。")}</p> : null}</section>; }

function DecisionCreate({ projectId, language, onCreated, onError }: { readonly projectId: string; readonly language: AppLanguage; readonly onCreated: (detail: DecisionDetailDto) => void; readonly onError: (error: unknown) => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  async function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const data = new FormData(event.currentTarget); const brief = await researchRoomApi.briefWorkspace(1); const scopeKind = formText(data.get("scopeKind"), "project"); const scopeId = formText(data.get("scopeId")).trim(); const scope = scopeKind === "project" ? { kind: "project" } : scopeKind === "artifact" ? { kind: "artifact", artifactId: scopeId } : scopeKind === "brief" ? { kind: "brief", briefVersionId: scopeId || brief.active.id } : { kind: "issue", issueId: scopeId }; const detail = await researchRoomApi.recordDecision({ projectId, expectedVersion: brief.entityVersion, effectiveBriefVersionId: brief.active.id, statement: formText(data.get("statement")), scope, rationale: formText(data.get("rationale")), reopenConditions: lines(data.get("reopenConditions")), reason: formText(data.get("reason")) }); onCreated(detail); } catch (error) { onError(error); } finally { setBusy(false); } }
  return <div>{!open ? <Button type="button" onClick={() => { setOpen(true); }}>{c(language, "Record proposed Decision", "记录 proposed Decision")}</Button> : <form className="popover-form" onSubmit={(event) => { void submit(event); }}><h2>{c(language, "Decision proposal", "Decision 提案")}</h2><label>{c(language, "Statement", "陈述")}<textarea name="statement" required /></label><label>{c(language, "Scope", "范围")}<select name="scopeKind"><option value="project">project</option><option value="artifact">artifact</option><option value="brief">brief</option><option value="issue">issue</option></select></label><label>{c(language, "Scope object ID (when needed)", "范围对象 ID（如需要）")}<input name="scopeId" /></label><label>{c(language, "Rationale", "依据")}<textarea name="rationale" required /></label><label>{c(language, "Reopen conditions", "重开条件")}<textarea name="reopenConditions" /></label><label>{c(language, "Command reason", "命令理由")}<textarea name="reason" required /></label><div className="form-actions"><Button type="button" variant="quiet" onClick={() => { setOpen(false); }}>{c(language, "Cancel", "取消")}</Button><Button type="submit" disabled={busy}>{c(language, "Record proposal", "记录提案")}</Button></div></form>}</div>;
}

function DecisionActions({ language, projectId, detail, onChanged, onError }: { readonly language: AppLanguage; readonly projectId: string; readonly detail: DecisionDetailDto; readonly onChanged: (next: DecisionDetailDto) => Promise<void>; readonly onError: (error: unknown) => void }) {
  const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [replacement, setReplacement] = useState(false);
  async function transition(target: "accepted" | "rejected" | "frozen") { setBusy(true); try { const next = await researchRoomApi.transitionDecision({ projectId, decisionId: detail.id, expectedVersion: detail.version, target, reason }); await onChanged(next); } catch (error) { onError(error); } finally { setBusy(false); } }
  async function supersede(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const data = new FormData(event.currentTarget); const result = await researchRoomApi.supersedeDecision({ projectId, decisionId: detail.id, expectedVersion: detail.version, effectiveBriefVersionId: detail.effectiveBriefVersionId, statement: formText(data.get("statement")), scope: detail.scope, rationale: formText(data.get("rationale")), reopenConditions: lines(data.get("conditions")), reason: formText(data.get("reason")) }); await onChanged(result.replacement); } catch (error) { onError(error); } finally { setBusy(false); } }
  return <section className="authority-gate"><h2>{c(language, "Decision Authority Gate", "Decision Authority Gate")}</h2><p>{c(language, "Core reports the legal actions below and validates the expected version again before writing. Nothing is committed optimistically.", "下列合法动作由 Core 投影给出；写入前还会再次校验 expected version，不会 optimistic commit。")}</p><p><strong>{c(language, "Available now", "当前可执行")}:</strong> {detail.availableActions.join(" · ") || c(language, "none", "无")}</p>{detail.availableActions.some((action) => ["accept", "reject", "freeze"].includes(action)) ? <label>{c(language, "Reason", "理由")}<textarea value={reason} onChange={(event) => { setReason(event.target.value); }} /></label> : null}<div className="disposition-grid"><Button type="button" disabled={busy || !reason.trim() || !detail.availableActions.includes("accept")} onClick={() => { void transition("accepted"); }}>{c(language, "Accept", "接受")}</Button><Button type="button" disabled={busy || !reason.trim() || !detail.availableActions.includes("reject")} variant="quiet" onClick={() => { void transition("rejected"); }}>{c(language, "Reject", "拒绝")}</Button><Button type="button" disabled={busy || !reason.trim() || !detail.availableActions.includes("freeze")} variant="quiet" onClick={() => { void transition("frozen"); }}>{c(language, "Freeze", "冻结")}</Button><Button type="button" disabled={busy || !detail.availableActions.includes("supersede")} variant="quiet" onClick={() => { setReplacement((current) => !current); }}>{c(language, "Supersede…", "替代……")}</Button></div>{replacement ? <form className="structured-editor" onSubmit={(event) => { void supersede(event); }}><h3>{c(language, "Replacement preview", "替代结果预览")}</h3><p>{c(language, "The current Decision remains in history as superseded; the replacement becomes accepted.", "当前 Decision 会作为 superseded 保留，替代项将成为 accepted。")}</p><label>{c(language, "Replacement statement", "替代陈述")}<textarea name="statement" required /></label><label>{c(language, "Rationale", "依据")}<textarea name="rationale" required /></label><label>{c(language, "Reopen conditions", "重开条件")}<textarea name="conditions" /></label><label>{c(language, "Supersede reason", "替代理由")}<textarea name="reason" required /></label><Button type="submit" disabled={busy}>{c(language, "Confirm supersede", "确认替代")}</Button></form> : null}</section>;
}

function IssueActions({ language, projectId, detail, onChanged, onError }: { readonly language: AppLanguage; readonly projectId: string; readonly detail: IssueDetailDto; readonly onChanged: () => Promise<void>; readonly onError: (error: unknown) => void }) {
  const [busy, setBusy] = useState(false);
  async function submit(action: "resolve" | "waive" | "dispute" | "reopen", event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const data = new FormData(event.currentTarget); const base = { projectId, issueId: detail.id, expectedVersion: detail.version, reason: formText(data.get("reason")) }; const input = action === "resolve" ? { ...base, resolutionEvidenceId: formText(data.get("evidenceId")) } : action === "waive" ? { ...base, scope: { kind: "issue", issueId: detail.id }, invalidationCondition: formText(data.get("invalidationCondition")) } : action === "reopen" ? { ...base, context: { userRequested: true } } : base; await researchRoomApi.issueCommand(action, input); await onChanged(); } catch (error) { onError(error); } finally { setBusy(false); } }
  return <section className="authority-gate"><h2>{c(language, "Issue Authority Gate", "Issue 权威门禁")}</h2><p>{c(language, "Closing this panel never changes the Issue. Core reports the legal actions; resolve still requires canonical project Evidence and waive preserves scope plus invalidation condition.", "关闭面板不会改变 Issue；合法动作由 Core 投影给出。解决仍必须绑定项目 canonical Evidence，豁免会保留范围与失效条件。")}</p><p><strong>{c(language, "Available now", "当前可执行")}:</strong> {detail.availableActions.join(" · ") || c(language, "none", "无")}</p>{detail.availableActions.length ? <div className="command-accordions">{detail.availableActions.includes("resolve") ? <details><summary>{c(language, "Resolve", "解决")}</summary><form onSubmit={(event) => { void submit("resolve", event); }}><label>{c(language, "Canonical Evidence ID", "Canonical Evidence ID（规范证据 ID）")}<input name="evidenceId" required /></label><label>{c(language, "Reason", "理由")}<textarea name="reason" required /></label><Button type="submit" disabled={busy}>{c(language, "Resolve", "解决")}</Button></form></details> : null}{detail.availableActions.includes("waive") ? <details><summary>{c(language, "Waive", "豁免")}</summary><form onSubmit={(event) => { void submit("waive", event); }}><p>{c(language, "scope", "范围")}: issue / {detail.id}</p><label>{c(language, "Invalidation condition", "失效条件")}<textarea name="invalidationCondition" required /></label><label>{c(language, "Reason", "理由")}<textarea name="reason" required /></label><Button type="submit" disabled={busy}>{c(language, "Waive", "豁免")}</Button></form></details> : null}{detail.availableActions.includes("dispute") ? <details><summary>{c(language, "Dispute", "提出异议")}</summary><form onSubmit={(event) => { void submit("dispute", event); }}><label>{c(language, "Reason", "理由")}<textarea name="reason" required /></label><Button type="submit" disabled={busy}>{c(language, "Dispute", "提出异议")}</Button></form></details> : null}{detail.availableActions.includes("reopen") ? <details><summary>{c(language, "Reopen", "重开")}</summary><form onSubmit={(event) => { void submit("reopen", event); }}><p>{c(language, "The reopen is recorded in history as a user-requested action.", "重开会作为 user-requested 动作写入历史。")}</p><label>{c(language, "Reason", "理由")}<textarea name="reason" required /></label><Button type="submit" disabled={busy}>{c(language, "Reopen", "重开")}</Button></form></details> : null}</div> : <p className="empty-state">{c(language, "No App command is legal from this canonical state.", "当前 canonical 状态没有可执行的 App 命令。")}</p>}</section>;
}

function ReceiptActions({ language, projectId, detail, onChanged, onError }: { readonly language: AppLanguage; readonly projectId: string; readonly detail: ObjectReceiptDetailDto; readonly onChanged: () => Promise<void>; readonly onError: (error: unknown) => void }) {
  const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  async function download() { setBusy(true); try { const blob = await researchRoomApi.downloadReceipt(detail.id); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${detail.id}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { onError(error); } finally { setBusy(false); } }
  async function rollback() { setBusy(true); try { await researchRoomApi.rollbackReceipt(projectId, detail.id, detail.version, reason); await onChanged(); } catch (error) { onError(error); } finally { setBusy(false); } }
  return <section className="authority-gate"><h2>{c(language, "Receipt actions", "Receipt 动作")}</h2><Button type="button" variant="quiet" disabled={busy} onClick={() => { void download(); }}>{c(language, "Download receipt", "下载凭证")}</Button>{detail.rollback.available ? <><label>{c(language, "Rollback reason", "回滚理由")}<textarea value={reason} onChange={(event) => { setReason(event.target.value); }} /></label><Button type="button" disabled={busy || !reason.trim()} onClick={() => { void rollback(); }}>{c(language, "Confirm rollback", "确认回滚")}</Button></> : <p className="empty-state">{c(language, "Rollback is unavailable for this receipt.", "这个 Receipt 当前不可回滚。")}</p>}</section>;
}

function relationLinks(detail: Detail): readonly { readonly label: string; readonly href: string }[] {
  const briefLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Brief ${id}`, href: "/project/brief" }));
  const decisionLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Decision ${id}`, href: `/project/decisions/${id}` }));
  const issueLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Issue ${id}`, href: `/project/issues/${id}` }));
  const evidenceLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Evidence ${id}`, href: `/project/evidence/${id}` }));
  const episodeLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Episode ${id}`, href: `/project/episodes/${id}` }));
  const receiptLinks = (ids: readonly string[]) => ids.map((id) => ({ label: `Receipt ${id}`, href: `/project/receipts/${id}` }));
  const links = detail.kind === "decision"
    ? [...briefLinks(detail.relatedBriefVersionIds), ...issueLinks(detail.relatedIssueIds), ...episodeLinks(detail.relatedEpisodeIds), ...receiptLinks(detail.relatedReceiptIds), ...(detail.supersedesDecisionId ? decisionLinks([detail.supersedesDecisionId]) : []), ...(detail.supersededByDecisionId ? decisionLinks([detail.supersededByDecisionId]) : [])]
    : detail.kind === "issue"
      ? [...briefLinks(detail.relatedBriefVersionIds), ...decisionLinks(detail.relatedDecisionIds), ...evidenceLinks(detail.relatedEvidenceIds), ...episodeLinks(detail.relatedEpisodeIds), ...receiptLinks(detail.relatedReceiptIds)]
      : detail.kind === "evidence"
        ? [...briefLinks(detail.relatedBriefVersionIds), ...decisionLinks(detail.relatedDecisionIds), ...issueLinks(detail.relatedIssueIds), ...episodeLinks(detail.relatedEpisodeIds)]
        : detail.kind === "episode"
          ? [...briefLinks(detail.lockedBrief ? [detail.lockedBrief.versionId] : []), ...decisionLinks(detail.relatedDecisionIds), ...issueLinks(detail.relatedIssueIds), ...receiptLinks(detail.relatedReceiptIds)]
          : [...briefLinks(detail.relatedBriefVersionIds), ...decisionLinks(detail.relatedDecisionIds), ...issueLinks(detail.relatedIssueIds), ...(detail.sourceEpisodeId ? episodeLinks([detail.sourceEpisodeId]) : [])];
  return [...new Map(links.map((item) => [item.href, item])).values()];
}

function summaryLine(item: Summary): string { return item.kind === "decision" ? `${item.scope.kind} · ${item.provenance.authority}/${item.provenance.actorKind} · Brief ${item.effectiveBriefVersionId} · v${item.version}${item.referencedByCurrentBrief ? " · current Brief" : ""}` : item.kind === "issue" ? `${item.issueKind} · ${item.provenance.authority}/${item.provenance.actorKind} · recurrence ${item.recurrenceCount} · v${item.version}${item.requiresUserAction ? " · user action required" : ""}` : item.kind === "evidence" ? `${item.evidenceKind} · ${item.inferenceCapacity} · ${item.provenance.authority}/${item.provenance.actorKind}` : item.kind === "episode" ? `${item.artifactId} · ${item.provenance.authority}/${item.provenance.actorKind} · v${item.version}` : `${item.providerStatus} · ${displayText(item.disposition.kind, "disposition")} · v${item.version}`; }
function ledgerTitle(language: AppLanguage, kind: LedgerKind): string { const names = { decision: ["Decision Ledger", "Decision 账本"], issue: ["Issue Ledger", "Issue 账本"], evidence: ["Evidence Ledger", "Evidence 账本"], episode: ["Episodes", "Episodes"], receipt: ["Receipt Center", "Receipt Center"] } as const; return c(language, names[kind][0], names[kind][1]); }
function ledgerDeck(language: AppLanguage, kind: LedgerKind): string { if (kind === "evidence") return c(language, "Only canonical Evidence already in structured project state is shown. No project files are scanned.", "只显示已进入项目结构化状态的 canonical Evidence；不会扫描项目普通文件。"); if (kind === "receipt") return c(language, "Durable disposition history, trace, download, and the existing rollback contract.", "查看持久处置历史、Trace、下载与既有 rollback 合同。"); return c(language, "A bounded, versioned view of canonical project state.", "这是 canonical 项目状态的受限、版本化视图。"); }
function emptyLedger(language: AppLanguage, kind: LedgerKind): string { if (kind === "evidence") return c(language, "No canonical Evidence is recorded. Sestina will not fill this state with fixtures or scan files.", "当前没有 canonical Evidence；Sestina 不会用 fixture 填充，也不会扫描文件。"); return c(language, `No ${kind} objects match the current filter.`, `当前筛选下没有 ${kind} 对象。`); }
