import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join, relative, sep } from "node:path";
import { pathToFileURL } from "node:url";

const CANONICAL_RELATIVE_PATH = "canonical/research-integrity.md";
const CODEX_SKILL_RELATIVE_PATH =
  "hosts/codex/sestina-research-integrity/SKILL.md";
const CODEX_METADATA_RELATIVE_PATH =
  "hosts/codex/sestina-research-integrity/agents/openai.yaml";
const GENERATED_TYPESCRIPT_RELATIVE_PATH = "src/generated/codex.ts";
const AGENT_CORRECTOR_CANONICAL_ROOT = "canonical/agent-corrector";
const AGENT_CORRECTOR_CODEX_ROOT = "hosts/codex/agent-corrector";
const AGENT_CORRECTOR_GENERATED_TYPESCRIPT_RELATIVE_PATH =
  "src/generated/agent-corrector.ts";
const AGENT_CORRECTOR_FILES = Object.freeze([
  "SKILL.md",
  "agents/openai.yaml",
  "references/drift-rubrics.md",
  "references/intervention-contract.md",
  "references/task-anchor.md",
] as const);

// Append a superseded generated bundle hash here before changing the canonical
// Skill or Codex metadata. This is the only hand-maintained ownership history.
const KNOWN_PREVIOUS_BUNDLE_HASHES = Object.freeze([
  "98c84a8953867ddaaff9cc23dabf290fa0679041bcfec324e0ba5e697ac3f490",
] as readonly string[]);

const CODEX_METADATA = `interface:
  display_name: "Sestina Research Integrity"
  short_description: "Keep research revisions aligned with the active Brief"
  default_prompt: "Use $sestina-research-integrity to revise this research work within the current Sestina Research Brief."
dependencies:
  tools:
    - type: "mcp"
      value: "sestina"
      description: "Read-only access to the current or invocation-frozen Sestina research context."
policy:
  allow_implicit_invocation: true
`;

export interface SkillGenerationCheck {
  readonly ok: boolean;
  readonly drifted: readonly string[];
}

export interface SkillGenerationWrite {
  readonly ok: true;
  readonly changed: readonly string[];
}

function normalizeLf(value: string): string {
  return `${value.replaceAll("\r\n", "\n").replaceAll("\r", "\n").replace(/\n*$/u, "")}\n`;
}

function portable(path: string): string {
  return path.split(sep).join("/");
}

function renderGeneratedTypescript(skill: string, metadata: string): string {
  const bundleHash = createHash("sha256")
    .update(skill, "utf8")
    .update("\0", "utf8")
    .update(metadata, "utf8")
    .digest("hex");
  const knownBundleHashes = [
    ...new Set([...KNOWN_PREVIOUS_BUNDLE_HASHES, bundleHash]),
  ];
  return normalizeLf(`// Generated by integrations/skills/generate.ts. Do not edit by hand.
export const CODEX_RESEARCH_INTEGRITY_SKILL = ${JSON.stringify(skill)};
export const CODEX_OPENAI_YAML = ${JSON.stringify(metadata)};
export const SESTINA_SKILL_BUNDLE_HASH = ${JSON.stringify(bundleHash)};
export const SESTINA_SKILL_KNOWN_BUNDLE_HASHES = Object.freeze(${JSON.stringify(knownBundleHashes)});
export const SESTINA_SKILL_GENERATED_FILES = Object.freeze({
  "SKILL.md": CODEX_RESEARCH_INTEGRITY_SKILL,
  "agents/openai.yaml": CODEX_OPENAI_YAML,
});
`);
}

function agentCorrectorBundleHash(files: ReadonlyMap<string, string>): string {
  const digest = createHash("sha256");
  for (const [path, content] of [...files].sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    digest
      .update(path, "utf8")
      .update("\0", "utf8")
      .update(content, "utf8")
      .update("\0", "utf8");
  }
  return digest.digest("hex");
}

function renderAgentCorrectorTypescript(
  files: ReadonlyMap<string, string>,
): string {
  const skill = files.get("SKILL.md");
  const metadata = files.get("agents/openai.yaml");
  if (skill === undefined || metadata === undefined)
    throw new Error("Agent Corrector canonical bundle is incomplete.");
  const references = Object.fromEntries(
    [...files].filter(([path]) => path.startsWith("references/")),
  );
  const generatedFiles = Object.fromEntries(files);
  return normalizeLf(`// Generated by integrations/skills/generate.ts. Do not edit by hand.
export const CODEX_AGENT_CORRECTOR_SKILL = ${JSON.stringify(skill)};
export const CODEX_AGENT_CORRECTOR_OPENAI_YAML = ${JSON.stringify(metadata)};
export const AGENT_CORRECTOR_REFERENCE_FILES = Object.freeze(${JSON.stringify(references)});
export const AGENT_CORRECTOR_BUNDLE_HASH = ${JSON.stringify(agentCorrectorBundleHash(files))};
export const AGENT_CORRECTOR_GENERATED_FILES = Object.freeze(${JSON.stringify(generatedFiles)});
`);
}

async function readAgentCorrectorCanonical(
  packageRoot: string,
): Promise<ReadonlyMap<string, string> | undefined> {
  try {
    await readFile(
      join(packageRoot, AGENT_CORRECTOR_CANONICAL_ROOT, "SKILL.md"),
      "utf8",
    );
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
  const files = new Map<string, string>();
  for (const relativePath of AGENT_CORRECTOR_FILES) {
    files.set(
      relativePath,
      normalizeLf(
        await readFile(
          join(packageRoot, AGENT_CORRECTOR_CANONICAL_ROOT, relativePath),
          "utf8",
        ),
      ),
    );
  }
  return files;
}

async function expectedArtifacts(
  packageRoot: string,
): Promise<ReadonlyMap<string, string>> {
  const canonical = normalizeLf(
    await readFile(join(packageRoot, CANONICAL_RELATIVE_PATH), "utf8"),
  );
  const metadata = normalizeLf(CODEX_METADATA);
  const artifacts = new Map([
    [CODEX_SKILL_RELATIVE_PATH, canonical],
    [CODEX_METADATA_RELATIVE_PATH, metadata],
    [
      GENERATED_TYPESCRIPT_RELATIVE_PATH,
      renderGeneratedTypescript(canonical, metadata),
    ],
  ]);
  const agentCorrector = await readAgentCorrectorCanonical(packageRoot);
  if (agentCorrector !== undefined) {
    for (const [relativePath, content] of agentCorrector) {
      artifacts.set(join(AGENT_CORRECTOR_CODEX_ROOT, relativePath), content);
    }
    artifacts.set(
      AGENT_CORRECTOR_GENERATED_TYPESCRIPT_RELATIVE_PATH,
      renderAgentCorrectorTypescript(agentCorrector),
    );
  }
  return artifacts;
}

export async function checkGeneratedSkill(
  packageRoot: string,
): Promise<SkillGenerationCheck> {
  const drifted: string[] = [];
  for (const [relativePath, expected] of await expectedArtifacts(packageRoot)) {
    try {
      const actual = await readFile(join(packageRoot, relativePath), "utf8");
      if (actual !== expected) drifted.push(portable(relativePath));
    } catch {
      drifted.push(portable(relativePath));
    }
  }
  return { ok: drifted.length === 0, drifted };
}

export async function writeGeneratedSkill(
  packageRoot: string,
): Promise<SkillGenerationWrite> {
  const changed: string[] = [];
  for (const [relativePath, expected] of await expectedArtifacts(packageRoot)) {
    const target = join(packageRoot, relativePath);
    let actual: string | undefined;
    try {
      actual = await readFile(target, "utf8");
    } catch {
      actual = undefined;
    }
    if (actual === expected) continue;
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, expected, "utf8");
    changed.push(portable(relativePath));
  }
  return { ok: true, changed };
}

async function main(args: readonly string[]): Promise<number> {
  if (args.length !== 1 || (args[0] !== "--write" && args[0] !== "--check")) {
    process.stderr.write("Usage: generate.ts --write|--check\n");
    return 2;
  }
  const packageRoot = import.meta.dirname;
  if (args[0] === "--write") {
    const result = await writeGeneratedSkill(packageRoot);
    process.stdout.write(
      result.changed.length === 0
        ? "Sestina Skill artifacts are already current.\n"
        : `Generated ${result.changed.length} Sestina Skill artifact(s).\n`,
    );
    return 0;
  }
  const result = await checkGeneratedSkill(packageRoot);
  if (result.ok) {
    process.stdout.write("Sestina Skill artifacts are synchronized.\n");
    return 0;
  }
  process.stderr.write(
    `Generated Sestina Skill drift: ${result.drifted.join(", ")}\n`,
  );
  return 1;
}

const entry = process.argv[1];
if (entry !== undefined && import.meta.url === pathToFileURL(entry).href) {
  process.exitCode = await main(process.argv.slice(2));
}

export const GENERATED_SKILL_PATHS = Object.freeze({
  canonical: CANONICAL_RELATIVE_PATH,
  codexSkill: CODEX_SKILL_RELATIVE_PATH,
  codexMetadata: CODEX_METADATA_RELATIVE_PATH,
  typescript: GENERATED_TYPESCRIPT_RELATIVE_PATH,
  agentCorrector: Object.freeze({
    canonicalRoot: AGENT_CORRECTOR_CANONICAL_ROOT,
    codexRoot: AGENT_CORRECTOR_CODEX_ROOT,
    typescript: AGENT_CORRECTOR_GENERATED_TYPESCRIPT_RELATIVE_PATH,
  }),
});

export function relativeGeneratedPath(
  packageRoot: string,
  path: string,
): string {
  return portable(relative(packageRoot, path));
}
