import {
  PILOT_CONSENT_VERSION,
  PILOT_KIT_VERSION,
  PILOT_PROTOCOL_VERSION,
  SHAREABLE_PILOT_EXPORT_SCHEMA_VERSION,
  type UnsignedShareablePilotExport,
} from "../src/index.js";

export function unsignedExport(
  overrides: Partial<UnsignedShareablePilotExport> = {},
): UnsignedShareablePilotExport {
  return {
    schemaVersion: SHAREABLE_PILOT_EXPORT_SCHEMA_VERSION,
    participantCode: "EXT-0001",
    sessionId: "ps_11111111111111111111111111111111",
    evidenceId: "pe_111111111111111111111111",
    sessionOrdinal: 1,
    participantRole: "external_researcher",
    hostEntry: "research_room",
    materialType: "paper",
    sessionDate: "2026-08-30",
    totalDurationMinutes: 55,
    releasePlatform: "windows_x64",
    distributionSource: "github_release",
    releaseSourceCommit: "2".repeat(40),
    releaseAssetSha256: "3".repeat(64),
    operatingMode: "ledger_only",
    distribution: {
      download: { outcome: "success", durationMinutes: 2 },
      checksumVerification: { outcome: "success", durationMinutes: 1 },
      extraction: { outcome: "success", durationMinutes: 1 },
      firstLaunch: { outcome: "success", durationMinutes: 4 },
      timeToRoomMinutes: 8,
      failurePoint: null,
    },
    journey: {
      project: "completed",
      brief: "completed",
      review: "completed",
      manifest: "completed",
      disposition: "completed",
      receipt: "completed",
      recovery: "not_needed",
      relaunch: "success",
    },
    localWebLifecycle: {
      outcome: "success",
      frictionSeverity: "none",
      blocking: false,
    },
    setup: { outcome: "success", durationMinutes: 8 },
    episode: { outcome: "completed", durationMinutes: 31 },
    exitResult: "completed",
    exitPoint: null,
    repeatCorrectionImpact: "reduced",
    findingAssessment: { necessary: 3, unnecessary: 1, uncertain: 0 },
    maintenanceBurden: {
      brief: 2,
      decision: 3,
      issue: 2,
      manifest: 2,
      recovery: 1,
    },
    secondUseObserved: false,
    preferredEntry: "research_room",
    desktopNeed: "none",
    desktopSolutionEvidence: "none",
    uiNeed: "no",
    syntheticCaseDiscussion: "undecided",
    wouldUseAgain: "yes",
    failureObserved: false,
    negativeFeedbackObserved: false,
    consentVersion: PILOT_CONSENT_VERSION,
    protocolVersion: PILOT_PROTOCOL_VERSION,
    pilotKitVersion: PILOT_KIT_VERSION,
    releaseVersion: "0.2.0",
    releaseChannel: "public_preview",
    releaseBuildId:
      "86469e5ccc3c3b593084c6207545a4d8bfd1d23f19016d1d63973b49052c3085",
    ...overrides,
  };
}
