export type { CheckerObservation, CheckerResult, ResearchChecker } from "./checker.js";
export { CheckerRegistry } from "./registry.js";
export { calculateReviewInputHash, parseReviewContext } from "./review-context.js";
export type {
  CheckerIdentity, CheckerKind, ReviewBriefBinding, ReviewContext, ReviewContextInput,
  ReviewDecisionBinding, ReviewEpisodeBinding, ReviewEvidenceBoundaryBinding, ReviewIssueBinding,
  ReviewProjectBinding, ReviewRevisionBinding, ReviewSnapshotBinding,
} from "./review-context.js";
export { createFinding, parseFinding } from "./finding.js";
export type { Finding, FindingConfidence, FindingPresentation, FindingProvenance, FindingSeverity, FindingTarget } from "./finding.js";
export { parseFindingEvidenceSpan } from "./finding-evidence.js";
export type { FindingEvidenceSpan } from "./finding-evidence.js";
export { appendReviewFindings, createReviewRun, finalizeReviewRun, parseReviewRun, runReview } from "./review-run.js";
export type { CheckerErrorRecord, ReviewRun, ReviewRunStatus } from "./review-run.js";
export { reviewErr, reviewError, reviewOk } from "./review-result.js";
export type { ReviewError, ReviewErrorCode, ReviewResult } from "./review-result.js";
export type { ReviewRunRepository } from "./repository/review-run-repository.js";
export { FreshnessChecker } from "./checkers/freshness-checker.js";
export type { FreshnessObservation } from "./checkers/freshness-checker.js";
export { FRESHNESS_REASONS, FRESHNESS_RATIONALE, FRESHNESS_RECOVERY } from "./checkers/freshness-reasons.js";
export type { FreshnessReason } from "./checkers/freshness-reasons.js";
export { findingIdFromFingerprint, reviewFingerprint } from "./checkers/fingerprint.js";
export { ScopeChecker } from "./checkers/scope-checker.js";
export type { ConfirmedScopeProposal, ScopeCheckInput, ScopeDocument } from "./checkers/scope-checker.js";
export { diffMarkdownBlocks } from "./diff/block-diff.js";
export type { BlockChange, BlockChangeOperation, BlockDiff } from "./diff/block-diff.js";
export { parseMarkdownStructure } from "./diff/markdown-structure.js";
export type { MarkdownBlock, MarkdownHeading, MarkdownStructure } from "./diff/markdown-structure.js";
export { parseProjectRelativePath } from "./diff/path-policy.js";
export { findingToIssueCandidate } from "./issue/finding-to-issue-candidate.js";
export type { FindingIssueCandidate } from "./issue/finding-to-issue-candidate.js";
export { decideFindingSuppression } from "./issue/suppression-decision.js";
export type { IssueLookupResult, SuppressionDecision } from "./issue/suppression-decision.js";
export { IssueIntegrityChecker } from "./checkers/issue-integrity-checker.js";
export type { IssueIntegrityInput } from "./checkers/issue-integrity-checker.js";
export { deriveReviewObligations } from "./outcome/obligation.js";
export type { ObligationSource, OutcomeDimension, ReviewObligation, UserReviewCheck } from "./outcome/obligation.js";
export { COVERAGE_STATUSES, deriveCoverage } from "./outcome/coverage.js";
export type { CoverageStatus, ObligationAssessment, ObligationCoverage } from "./outcome/coverage.js";
export { compareFindingSeverity, isBlockingCoverageStatus, isForegroundFinding } from "./outcome/severity-policy.js";
export { deriveReviewOutcome } from "./outcome/derive-outcome.js";
export type { DimensionOutcome, ReviewOutcome, UserReviewDisposition } from "./outcome/derive-outcome.js";
export { SEMANTIC_FINDING_KINDS, isSemanticFindingKind } from "./semantic/semantic-finding-kind.js";
export type { SemanticFindingKind } from "./semantic/semantic-finding-kind.js";
export { createStableTextDocument, createStableTextSpan, normalizeStableText, validateStableTextSpan, STABLE_TEXT_INDEX_UNIT, STABLE_TEXT_NORMALIZATION_VERSION } from "./semantic/stable-text-span.js";
export type { StableTextDocument, StableTextDocumentInput, StableTextSpan } from "./semantic/stable-text-span.js";
export { SEMANTIC_REVIEW_RESPONSE_SCHEMA } from "./semantic/semantic-review-schema.js";
export { prepareSemanticReview } from "./semantic/prepare-semantic-review.js";
export type { PrepareSemanticReviewInput, SemanticBriefContext, SemanticCriterion, SemanticDecisionContext, SemanticReviewLimits, SemanticReviewRequest } from "./semantic/semantic-review-request.js";
export { submitSemanticReview } from "./semantic/submit-semantic-review.js";
export type { SemanticFindingProposal, SemanticReviewerMetadata, SemanticReviewProposal } from "./semantic/semantic-review-response.js";
export { parseUntrustedJson, semanticReviewErr, semanticReviewOk } from "./semantic/untrusted-response.js";
export type { SemanticReviewError, SemanticReviewErrorCode, SemanticReviewResult } from "./semantic/untrusted-response.js";
export { parseMinimalRecovery, parseResearchIntent, summarizeSemanticFixtureRun } from "./semantic/rubrics/shared-intent.js";
export type { MinimalRecoveryAction, ResearchIntent, StructuredSemanticRubric } from "./semantic/rubrics/shared-intent.js";
export { FOCUS_SUBSTITUTION_RUBRIC, validateFocusSubstitutionAssessment } from "./semantic/rubrics/focus-substitution.js";
export type { FocusSubstitutionAssessment, FocusSubstitutionVerdict, IntentRelationship } from "./semantic/rubrics/focus-substitution.js";
export { AUDIT_HIJACKING_RUBRIC, validateAuditHijackingAssessment } from "./semantic/rubrics/audit-hijacking.js";
export type { AuditClassification, AuditHijackingAssessment } from "./semantic/rubrics/audit-hijacking.js";
export { SEMANTIC_SCOPE_RUBRIC, resolveScopeAssessment, validateSemanticScopeAssessment } from "./semantic/rubrics/semantic-scope.js";
export type { DeterministicScopeResult, ResolvedScopeAssessment, ScopeChangeRelationship, SemanticScopeAssessment, SemanticScopeCategory, SemanticScopeChange } from "./semantic/rubrics/semantic-scope.js";
export { DECISION_INTEGRITY_RUBRIC, validateDecisionIntegrityAssessment } from "./semantic/rubrics/decision-integrity.js";
export type { DecisionConflict, DecisionConflictRelationship, DecisionIntegrityAssessment, SuppliedDecisionContext } from "./semantic/rubrics/decision-integrity.js";
export { ARGUMENT_DELTA_RUBRIC, validateArgumentDeltaAssessment } from "./semantic/rubrics/argument-delta.js";
export type { ArgumentDeltaAssessment } from "./semantic/rubrics/argument-delta.js";
export { SHALLOW_ABSTRACTION_RUBRIC, validateShallowAbstractionAssessment } from "./semantic/rubrics/shallow-abstraction.js";
export type { ShallowAbstractionAssessment } from "./semantic/rubrics/shallow-abstraction.js";
export { EVIDENCE_BOUNDARY_RUBRIC, evaluateEvidenceBoundary } from "./semantic/rubrics/evidence-boundary.js";
export type { EvidenceBoundaryCode, EvidenceBoundaryFinding, EvidenceBoundaryInput } from "./semantic/rubrics/evidence-boundary.js";
export { EvidenceFreshnessChecker, evaluateEvidenceFreshness } from "./checkers/evidence-freshness-checker.js";
export type { CurrentEvidenceRevision, EvidenceFreshnessIssue } from "./checkers/evidence-freshness-checker.js";
export { mergeFindings } from "./findings/merge-findings.js";
export type { MergedFinding } from "./findings/merge-findings.js";
export { compareMergedFindings, findingPriority, findingRootCauseKey, rankFindings } from "./findings/rank-findings.js";
export type { FindingPriority } from "./findings/rank-findings.js";
export { DEFAULT_FOREGROUND_FINDING_LIMIT, projectFindings, selectProjectedFindings } from "./findings/intervention-budget.js";
export type { FindingProjection, FindingProjectionMetrics, FindingProjectionOptions, RawFindingProjection, SuppressedFindingProjection } from "./findings/intervention-budget.js";
export { preservePositive } from "./findings/preserve-positive.js";
export type { PreservedPositiveProjection } from "./findings/preserve-positive.js";
